import type { Metadata } from "next";
import { ArrowRight, Check, FileText, LayoutTemplate, ScanSearch, ShieldCheck } from "lucide-react";
import { ButtonLink } from "@/components/ui/button-link";
import { PageHero } from "@/components/marketing/page-hero";

export const metadata: Metadata = { title: "Custom Compliance Web Design", description: "Custom merchant websites designed around clear policies, controlled claims, age and intended-use gates, checkout disclosures, and ongoing ORBIT monitoring." };

const stages = [
  { title: "Risk and content blueprint", text: "We map products, claims, policies, audiences, checkout states and required controls before visual design begins.", icon: ScanSearch },
  { title: "Custom experience design", text: "A bespoke storefront and design system built around the merchant brand, without generic templates or developer-dashboard aesthetics.", icon: LayoutTemplate },
  { title: "Compliance architecture", text: "Terms, privacy, refunds, shipping, contact, age and intended-use language are placed where customers and reviewers can actually find them.", icon: FileText },
  { title: "Launch validation", text: "Responsive QA, route checks, visual evidence capture and an ORBIT baseline assessment establish the first monitored state.", icon: ShieldCheck },
];

export default function CustomCompliancePage() {
  return <><PageHero eyebrow="Custom web design" title="Websites that earn trust before anyone reads the fine print." description="ORBIT designs polished merchant experiences with compliance controls embedded into product content, policy architecture and checkout UX." primary={false}/><section className="border-y border-white/[.07] bg-[#0a0b0e] py-24 sm:py-32"><div className="container-shell"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">The engagement</p><h2 className="mt-6 text-balance text-4xl font-medium leading-[1] tracking-[-.05em] sm:text-6xl">Brand, commerce and risk controls in one build.</h2><p className="mt-6 max-w-md text-sm leading-7 text-[#888c94]">For research products, supplements, cosmetics, high-risk ecommerce and other businesses that cannot afford a disconnected design and compliance process.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.08] sm:grid-cols-2">{stages.map(({title,text,icon:Icon},index)=><article key={title} className="bg-[#0d0f12] p-6 sm:p-8"><div className="flex items-center justify-between"><Icon className="size-5 text-[#9698f3]"/><span className="font-mono text-[9px] text-[#555a62]">0{index+1}</span></div><h3 className="mt-12 text-xl font-medium tracking-[-.03em]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#7d8189]">{text}</p></article>)}</div></div></div></section><section className="bg-[#ece8de] py-24 text-[#171713] sm:py-32"><div className="container-shell grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-[#66635c]">What ships</p><h2 className="mt-5 text-4xl font-medium tracking-[-.05em] sm:text-6xl">A production-ready merchant presence.</h2></div><div><ul className="grid gap-3 sm:grid-cols-2">{["Responsive storefront system","Product and category templates","Policy and contact surfaces","Age / intended-use controls","Checkout disclosure design","Analytics-ready events","Accessibility review","ORBIT monitoring baseline"].map(item=><li key={item} className="flex items-center gap-3 border-b border-black/10 py-3 text-sm"><Check className="size-4 text-[#4b8d71]"/>{item}</li>)}</ul><div className="mt-8 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/request-access" className="bg-[#171713] text-white hover:bg-black">Request a design consultation</ButtonLink><ButtonLink href="/contact" variant="ghost" className="text-[#33322e] hover:text-black">Discuss scope <ArrowRight className="size-4"/></ButtonLink></div></div></div></section></>;
}
