import Link from "next/link";
import { Download, FileSpreadsheet, FileText, ShieldCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { getPortalContext } from "@/merchant-portal/access";
import { getServerEnv } from "@/sentinel/config";
import { formatMinor } from "@/statements/calculation";
import { listMerchantStatements } from "@/statements/data";

type Query = { year?: string | string[] };
const periodName = (date: Date) => new Intl.DateTimeFormat("en-US", { month: "long", year: "numeric", timeZone: getServerEnv().STATEMENT_TIMEZONE }).format(date);
const shortDate = (date: Date | null) => date ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: getServerEnv().STATEMENT_TIMEZONE }).format(date) : "—";

export default async function StatementsPage({ searchParams }: { searchParams: Promise<Query> }) {
  if (!getServerEnv().STATEMENTS_ENABLED) notFound();
  const [{ merchant }, query] = await Promise.all([getPortalContext(), searchParams]);
  if (!merchant) return null;
  const currentYear = new Date().getUTCFullYear();
  const requested = typeof query.year === "string" ? Number(query.year) : currentYear;
  const year = Number.isInteger(requested) && requested >= 2020 && requested <= currentYear + 1 ? requested : currentYear;
  const { statements, summaries } = await listMerchantStatements(merchant.id, year);
  const years = Array.from({ length: 5 }, (_, index) => currentYear - index);
  return <div className="mx-auto w-full max-w-[1540px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10">
    <header className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.14em] text-[#a99cff]"><FileText className="size-3.5" />ORBIT Payment · Reporting</p><h1 className="mt-3 text-[30px] font-semibold tracking-[-.055em] text-white sm:text-[38px]">Statements</h1><p className="mt-2 text-[11px] text-[#777d89]">Monthly financial activity, payouts, fees and account reconciliation.</p></div><form className="flex gap-2"><label htmlFor="statement-year" className="sr-only">Statement year</label><select id="statement-year" name="year" defaultValue={year} className="h-10 rounded-xl border border-white/[.1] bg-[#101218] px-4 text-[11px] text-[#d8dae0]">{years.map((item) => <option key={item}>{item}</option>)}</select><button className="h-10 rounded-xl border border-[#8f7dff]/25 bg-[#8f7dff]/10 px-4 text-[10px] font-semibold text-[#b8affb]">View</button></form></header>
    {summaries.map((summary) => <section key={summary.currency} className="mt-7" aria-label={`${summary.currency} annual totals`}><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><h2 className="text-[11px] font-semibold uppercase tracking-[.14em] text-[#8a9099]">{summary.currency} · {year} year to date</h2><div className="flex gap-2"><Link href={`/api/portal/statements/annual/csv?year=${year}&currency=${summary.currency}`} className="inline-flex h-8 items-center gap-1.5 rounded-lg border border-white/[.08] px-3 text-[9px] text-[#aeb2bc]"><FileSpreadsheet className="size-3" />CSV</Link><Link href={`/api/portal/statements/annual/pdf?year=${year}&currency=${summary.currency}`} className="inline-flex h-8 items-center gap-1.5 rounded-lg border border-white/[.08] px-3 text-[9px] text-[#aeb2bc]"><Download className="size-3" />Annual PDF</Link></div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[
      ["Gross volume", summary.grossPaymentsMinor], ["Refunds", -summary.refundsMinor], ["Processing fees", -summary.processingFeesMinor], ["ORBIT fees", -summary.orbitFeesMinor], ["Net activity", summary.netActivityMinor], ["Payouts", summary.payoutsMinor],
    ].map(([label, amount]) => <div key={String(label)} className="orbit-finance-card rounded-[18px] border border-white/[.075] p-4"><p className="text-[8px] font-semibold uppercase tracking-[.1em] text-[#6f7581]">{String(label)}</p><p className="mt-3 text-[19px] font-semibold tabular-nums text-white">{formatMinor(amount as bigint, summary.currency)}</p></div>)}</div></section>)}
    <section className="mt-8 overflow-hidden rounded-[24px] border border-white/[.075] bg-[#0b0d13] shadow-[0_30px_90px_rgba(0,0,0,.18)]"><div className="flex items-center justify-between border-b border-white/[.07] px-5 py-5 sm:px-7"><div><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#777d89]">Monthly archive</p><h2 className="mt-2 text-[18px] font-semibold text-white">{year} statements</h2></div><ShieldCheck className="size-4 text-[#8f82ef]" /></div>
      {statements.length ? <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left"><thead><tr className="border-b border-white/[.06] bg-white/[.018]">{["Period", "Statement ID", "Gross volume", "Fees", "Net activity", "Payouts", "Status", "Generated", "Email", "Actions"].map((heading) => <th key={heading} className="px-4 py-3 text-[8px] font-semibold uppercase tracking-[.08em] text-[#626874] first:pl-7">{heading}</th>)}</tr></thead><tbody>{statements.map((statement) => <tr key={statement.id} className="border-b border-white/[.055] last:border-0 hover:bg-[#8f7dff]/[.035]"><td className="py-5 pl-7 pr-4 text-[11px] font-medium text-[#e1e3e8]">{periodName(statement.periodStart)} <span className="ml-1 text-[8px] text-[#8276df]">{statement.currency}</span></td><td className="px-4 font-mono text-[8px] text-[#9e91f4]">{statement.publicId}</td><td className="px-4 text-[10px] tabular-nums text-[#dfe1e6]">{formatMinor(statement.grossPaymentsMinor, statement.currency)}</td><td className="px-4 text-[10px] tabular-nums text-[#a7abb5]">{formatMinor(statement.processingFeesMinor + statement.orbitFeesMinor, statement.currency)}</td><td className="px-4 text-[10px] font-semibold tabular-nums text-white">{formatMinor(statement.netActivityMinor, statement.currency)}</td><td className="px-4 text-[10px] tabular-nums text-[#a7abb5]">{formatMinor(statement.payoutsMinor, statement.currency)}</td><td className="px-4"><span className="rounded-full border border-[#65d1aa]/15 bg-[#65d1aa]/[.06] px-2 py-1 text-[8px] text-[#83d8b8]">{statement.status.replaceAll("_", " ")}</span></td><td className="px-4 text-[9px] text-[#777d89]">{shortDate(statement.generatedAt)}</td><td className="px-4 text-[9px] text-[#777d89]">{statement.emailStatus.replaceAll("_", " ")}</td><td className="px-4"><div className="flex gap-3"><Link href={`/dashboard/statements/${statement.publicId}`} className="text-[9px] font-semibold text-[#aea4fa]">View</Link>{statement.status === "FINALIZED" && <><Link href={`/api/portal/statements/${statement.publicId}/pdf`} className="text-[9px] text-[#8e94a0]">PDF</Link><Link href={`/api/portal/statements/${statement.publicId}/csv`} className="text-[9px] text-[#8e94a0]">CSV</Link></>}</div></td></tr>)}</tbody></table></div> : <div className="px-6 py-20 text-center"><span className="mx-auto grid size-12 place-items-center rounded-2xl border border-[#8f7dff]/15 bg-[#8f7dff]/[.07] text-[#9f93f5]"><FileText className="size-4" /></span><h2 className="mt-4 text-[15px] font-semibold text-white">No statements yet</h2><p className="mx-auto mt-2 max-w-md text-[10px] leading-5 text-[#6f7581]">Your first monthly statement will appear here after the reporting period closes.</p></div>}
    </section><p className="mt-5 text-[9px] leading-5 text-[#666c78]">Statements are provided for account reconciliation and recordkeeping. Tax documents, when applicable, are provided separately.</p>
  </div>;
}
