import { Activity, AlertTriangle, ArrowRight, CheckCircle2, CircleGauge, HeartPulse, ShieldCheck } from "lucide-react";
import { MerchantPortalLink } from "@/components/merchant-portal/merchant-portal-link";
import { customerMerchantIds } from "@/customers/data";
import { getPortalContext } from "@/merchant-portal/access";
import { getMerchantHealth } from "@/operations/health";

const levelStyle = { healthy: "text-[#78d1b0] border-[#63caa5]/20 bg-[#63caa5]/[.06]", attention: "text-[#d7b274] border-[#d7ad68]/20 bg-[#d7ad68]/[.06]", critical: "text-[#e69aa4] border-[#db7b88]/20 bg-[#db7b88]/[.06]" };

export default async function HealthPage() {
  const { merchant, merchants, session } = await getPortalContext();
  const scope = customerMerchantIds(session.role, merchant?.id ?? null, merchants.map((item) => item.id));
  const health = await getMerchantHealth(scope);
  const average = health.length ? Math.round(health.reduce((sum, item) => sum + item.score, 0) / health.length) : 0;
  return <div className="mx-auto w-full max-w-[1440px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10"><header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.14em] text-[#a99cff]"><HeartPulse className="size-3.5" />ORBIT intelligence</p><h1 className="mt-3 text-[30px] font-semibold tracking-[-.055em] text-white sm:text-[38px]">Merchant health</h1><p className="mt-2 text-[11px] text-[#777d89]">One score combining financial readiness, payment performance, reporting, commerce and compliance.</p></div><div className="flex items-center gap-3 rounded-2xl border border-white/[.075] bg-[#0b0d13] px-5 py-3"><CircleGauge className="size-5 text-[#9182f0]" /><div><p className="text-[8px] uppercase tracking-[.1em] text-[#626874]">Portfolio average</p><p className="mt-1 text-[20px] font-semibold text-white">{average}<span className="text-[10px] text-[#6d7380]">/100</span></p></div></div></header>
    <section className="mt-7 grid gap-5 xl:grid-cols-2">{health.map((item) => <article key={item.merchantId} className="overflow-hidden rounded-[24px] border border-white/[.075] bg-[#0b0d13]"><div className="flex items-start justify-between gap-4 border-b border-white/[.06] p-5 sm:p-6"><div><p className="text-[16px] font-semibold text-white">{item.merchantName}</p><span className={`mt-3 inline-flex rounded-full border px-2.5 py-1 text-[8px] font-semibold uppercase tracking-[.08em] ${levelStyle[item.level]}`}>{item.level}</span></div><div className="relative grid size-20 place-items-center rounded-full" style={{ background: `conic-gradient(#8f7dff ${item.score * 3.6}deg, rgba(255,255,255,.06) 0deg)` }}><span className="grid size-[68px] place-items-center rounded-full bg-[#0b0d13] text-[21px] font-semibold text-white">{item.score}</span></div></div><div className="p-5 sm:p-6"><div className="space-y-4">{item.components.map((component) => <div key={component.label}><div className="flex items-center justify-between text-[9px]"><span className="text-[#aeb2bb]">{component.label}</span><span className="text-[#777d89]">{component.score}/{component.maximum} · {component.status}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/[.05]"><div className="h-full rounded-full bg-gradient-to-r from-[#6e5be3] to-[#9f8fff]" style={{ width: `${(component.score / component.maximum) * 100}%` }} /></div></div>)}</div>{item.actions.length ? <div className="mt-6 rounded-2xl border border-[#d7ad68]/12 bg-[#d7ad68]/[.035] p-4"><p className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.1em] text-[#c5a66f]"><AlertTriangle className="size-3.5" />Recommended actions</p><ul className="mt-3 space-y-2">{item.actions.map((action) => <li key={action} className="flex gap-2 text-[9px] leading-4 text-[#898078]"><ArrowRight className="mt-0.5 size-3 shrink-0" />{action}</li>)}</ul></div> : <div className="mt-6 flex items-center gap-2 rounded-2xl border border-[#63caa5]/12 bg-[#63caa5]/[.035] p-4 text-[9px] text-[#7fc9ae]"><CheckCircle2 className="size-3.5" />No immediate operational actions detected.</div>}<MerchantPortalLink merchantId={item.merchantId} href="/dashboard?view=brand" className="mt-5 inline-flex items-center gap-2 text-[9px] font-semibold text-[#a99cff]"><Activity className="size-3.5" />Open brand overview</MerchantPortalLink></div></article>)}{!health.length && <div className="col-span-full px-6 py-20 text-center"><ShieldCheck className="mx-auto size-6 text-[#8f82ef]" /><p className="mt-4 text-[11px] text-[#6f7581]">No merchant accounts are available.</p></div>}</section>
  </div>;
}
