"use client";

import Link from "next/link";
import { AlertTriangle, ArrowLeft, ArrowRight, Check, Circle, LoaderCircle, Network, ScanLine } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { sentinelFetch } from "./client";
import { cn } from "@/lib/utils";

type Progress = { stage: string; message: string; urlsFound: number; pagesProcessed: number; pagesTotal: number; productsDetected: number; productsDiscovered?: number; productsScanned?: number; variantsScanned?: number; imagesAnalyzed?: number; certificatesDiscovered?: number; certificatesAnalyzed?: number; checkoutFlowsInspected?: number; scanCoveragePercent?: number; policiesDetected: number; claimsInspected: number; findings: number; attempt?: number; recoveredPages?: number; stageProcessed?: number; stageTotal?: number; currentUrl?: string; updatedAt: string };
type Scan = { id: string; merchantId: string; status: string; mode: string; progress: Progress; pagesDiscovered: number; pagesProcessed: number; productsDetected: number; policiesDetected: number; findingsCreated: number; scoreBefore?: number; scoreAfter?: number; error?: string; createdAt: string; completedAt?: string; changes: Array<{ id: string; type: string; riskImpact: string; summary?: string; diff: { additions?: string[]; removals?: string[] }; scanPage: { url: string; title?: string } }> };
const order = ["queued", "discovering", "crawling", "classifying", "analyzing", "evidence", "scoring", "completed"];

export function LiveScan({ scanId }: { scanId: string }) {
  const [scan, setScan] = useState<Scan>(); const [error, setError] = useState("");
  const load = useCallback(async () => { try { const data = await sentinelFetch<{ scan: Scan }>(`/api/sentinel/scans/${scanId}`); setScan(data.scan); setError(""); return data.scan; } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load scan"); } }, [scanId]);
  useEffect(() => { let active = true; let timer: ReturnType<typeof setTimeout>; const poll = async () => { const current = await load(); if (active && current && !["COMPLETED", "FAILED", "CANCELLED"].includes(current.status)) timer = setTimeout(poll, 1400); }; void poll(); return () => { active = false; clearTimeout(timer); }; }, [load]);
  if (!scan && !error) return <div className="grid min-h-[calc(100dvh-56px)] place-items-center"><LoaderCircle className="size-5 animate-spin text-[#8588ef]" /></div>;
  if (!scan) return <div className="p-8 text-xs text-[#d68b8b]">{error}</div>;
  const progress = scan.progress ?? { stage: scan.status.toLowerCase(), message: scan.status, urlsFound: 0, pagesProcessed: scan.pagesProcessed, pagesTotal: scan.pagesDiscovered, productsDetected: scan.productsDetected, policiesDetected: scan.policiesDetected, claimsInspected: 0, findings: scan.findingsCreated, updatedAt: scan.createdAt };
  const currentIndex = scan.status === "FAILED" ? -1 : order.indexOf(progress.stage);
  const overallProgress = scanProgressPercent(scan, progress);
  const elapsed = formatElapsed(scan.createdAt, scan.completedAt);
  return <div className="mx-auto max-w-[1280px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10"><Link href={`/sentinel/merchant/${scan.merchantId}`} className="inline-flex items-center gap-1.5 text-[10px] text-[#6b6f77] hover:text-[#b8bab5]"><ArrowLeft className="size-3" />Merchant</Link><header className="mt-5 flex flex-col gap-4 border-b border-white/[.07] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-[#8588ef]">ORBIT Sentinel</p><span className="rounded border border-white/[.08] px-1.5 py-0.5 font-mono text-[8px] text-[#656a72]">{scan.id.slice(-8)}</span></div><h1 className="mt-2 text-2xl font-medium tracking-[-.04em]">{scan.status === "COMPLETED" ? "Scan complete" : scan.status === "FAILED" ? "Scan interrupted" : "Website intelligence in progress"}</h1><p className="mt-2 text-xs text-[#747881]">{progress.message}</p></div><div className="flex items-center gap-2 text-[10px] text-[#6a6e77]">{scan.status === "COMPLETED" ? <Check className="size-3.5 text-[#6fc69d]" /> : scan.status === "FAILED" ? <AlertTriangle className="size-3.5 text-[#d98282]" /> : <LoaderCircle className="size-3.5 animate-spin text-[#8588ef]" />}{scan.status.replaceAll("_", " ")}</div></header>
    <section aria-label="Overall scan progress" className="mt-6 border border-white/[.075] bg-[#0c0e12] p-4 sm:p-5">
      <div className="flex items-end justify-between gap-4"><div><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#666b74]">Pipeline progress</p><p className="mt-1.5 text-xs capitalize text-[#c9cbc6]">{progress.stage.replaceAll("_", " ")}</p></div><p className="font-mono text-2xl font-medium tracking-[-.05em] text-[#e2e3df]">{overallProgress}<span className="ml-0.5 text-xs text-[#777b84]">%</span></p></div>
      <div className="mt-4 h-2 overflow-hidden rounded-full bg-white/[.055]"><div className={cn("relative h-full rounded-full bg-[#8588ef] transition-[width] duration-700 ease-out", !["COMPLETED", "FAILED", "CANCELLED"].includes(scan.status) && "after:absolute after:inset-y-0 after:right-0 after:w-10 after:bg-gradient-to-r after:from-transparent after:to-white/35")} style={{ width: `${overallProgress}%` }} /></div>
      <div className="mt-3 grid grid-cols-4 gap-3 text-[9px]"><div><span className="block text-[#555a62]">Elapsed</span><span className="mt-1 block font-mono text-[#92969e]">{elapsed}</span></div><div className="text-center"><span className="block text-[#555a62]">Pages</span><span className="mt-1 block font-mono text-[#92969e]">{progress.pagesProcessed} / {Math.max(progress.pagesTotal, scan.pagesDiscovered)}</span></div><div className="text-center"><span className="block text-[#555a62]">Attempt</span><span className="mt-1 block font-mono text-[#92969e]">{progress.attempt ?? 1}{progress.recoveredPages ? ` · ${progress.recoveredPages} recovered` : ""}</span></div><div className="text-right"><span className="block text-[#555a62]">Updated</span><span className="mt-1 block font-mono text-[#92969e]">{formatUpdated(progress.updatedAt)}</span></div></div>
      <p className="mt-3 border-t border-white/[.055] pt-3 text-[9px] leading-4 text-[#555a62]">Progress is calculated from completed pipeline stages and observed page processing. Scan time varies with website size and response speed.</p>
    </section>
    {scan.error && <div className="mt-5 border border-[#d77979]/20 bg-[#d77979]/5 p-4 text-xs text-[#d99494]">{scan.error}</div>}
    <div className="mt-7 grid gap-7 lg:grid-cols-[.72fr_1.28fr]"><section><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#62666f]">Pipeline</p><ol className="mt-4">{order.map((stage, index) => { const done = currentIndex > index || progress.stage === "completed"; const active = currentIndex === index && progress.stage !== "completed"; return <li key={stage} className="relative flex min-h-12 gap-3 pl-1 after:absolute after:left-[9px] after:top-6 after:h-[calc(100%-16px)] after:w-px after:bg-white/[.07] last:after:hidden">{done ? <span className="relative z-10 grid size-[18px] place-items-center rounded-full bg-[#6fbe99] text-[#08100c]"><Check className="size-2.5" /></span> : active ? <span className="relative z-10 grid size-[18px] place-items-center rounded-full border border-[#8285ef] bg-[#15172b]"><span className="size-1.5 animate-pulse rounded-full bg-[#8d90f3]" /></span> : <span className="relative z-10 grid size-[18px] place-items-center rounded-full bg-[#171a1f]"><Circle className="size-2 text-[#4e535b]" /></span>}<div><p className={cn("text-[10px] capitalize", active ? "text-[#d2d4cf]" : done ? "text-[#8b8f87]" : "text-[#555a62]")}>{stage}</p>{active && <p className="mt-1 max-w-[260px] truncate text-[9px] text-[#646870]">{progress.currentUrl ?? progress.message}</p>}</div></li>; })}</ol></section>
      <section className="relative overflow-hidden border border-white/[.075] bg-[#0c0e12] p-5 sm:p-7"><div className="absolute inset-x-0 top-0 h-px bg-[#8588ef]/50 shadow-[0_0_18px_#777aec]" /><div className="flex items-center justify-between"><div className="flex items-center gap-2"><ScanLine className="size-4 text-[#8588ef]" /><h2 className="text-xs font-medium">Activity map</h2></div><span className="font-mono text-[9px] text-[#555a62]">REAL JOB STATE</span></div><div className="mt-7 border-l border-white/[.09] pl-5"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-md border border-[#7d80eb]/20 bg-[#7d80eb]/6"><Network className="size-4 text-[#8588ef]" /></span><div><p className="text-xs">Website</p><p className="mt-0.5 text-[9px] text-[#5e626b]">{progress.currentUrl ? safeHost(progress.currentUrl) : "Discovery root"}</p></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{[["URLs discovered", scan.pagesDiscovered || progress.urlsFound], ["Pages processed", progress.pagesProcessed], ["Products mapped", progress.productsDetected || scan.productsDetected], ["Policies found", progress.policiesDetected || scan.policiesDetected], ["Claims inspected", progress.claimsInspected], ["Findings built", progress.findings || scan.findingsCreated]].map(([label, value]) => <div key={label} className="flex items-center justify-between border-b border-white/[.055] py-3 text-[10px]"><span className="text-[#747880]">{label}</span><span className="font-mono text-[#c9cbc6]">{value}</span></div>)}</div></div><div className="mt-7"><div className="flex justify-between text-[9px] text-[#5f636c]"><span>Pages processed</span><span>{progress.pagesProcessed} / {Math.max(progress.pagesTotal, scan.pagesDiscovered)}</span></div><div className="mt-2 h-1 overflow-hidden rounded bg-white/[.055]"><div className="h-full bg-[#7d80eb] transition-[width] duration-500" style={{ width: `${Math.min(100, Math.max(2, (progress.pagesProcessed / Math.max(1, progress.pagesTotal || scan.pagesDiscovered)) * 100))}%` }} /></div></div></section></div>
    {scan.status === "COMPLETED" && <section className="mt-8"><div className="flex flex-col gap-4 border border-white/[.075] bg-[#0c0e12] p-5 sm:flex-row sm:items-center"><div><p className="text-[9px] uppercase tracking-[.14em] text-[#676b74]">ORBIT Health</p><p className="mt-1 text-3xl font-medium tracking-[-.05em]">{scan.scoreAfter}</p><p className="mt-1 text-[9px] text-[#555a62]">0 weakest · 100 strongest</p></div><div className="sm:ml-5 sm:border-l sm:border-white/[.07] sm:pl-5"><p className="text-xs text-[#bbbdb8]">{scan.findingsCreated} evidence-backed findings observed</p><p className="mt-1 text-[10px] text-[#62666e]">{scan.pagesProcessed} pages · {progress.productsScanned ?? scan.productsDetected} products · {scan.policiesDetected} policies · {progress.scanCoveragePercent ?? 0}% observed coverage</p><p className="mt-1 text-[9px] text-[#555a62]">{progress.imagesAnalyzed ?? 0} image metadata records · {progress.certificatesDiscovered ?? 0} certificate links discovered · {progress.checkoutFlowsInspected ?? 0} public cart/checkout views</p></div><Link href={`/sentinel/merchant/${scan.merchantId}`} className="inline-flex h-9 items-center justify-center gap-2 rounded-md bg-[#e9eae6] px-4 text-[10px] font-medium text-black sm:ml-auto">Open merchant view<ArrowRight className="size-3" /></Link></div>{scan.changes.length > 0 && <div className="mt-7"><h2 className="text-sm font-medium">Change Intelligence</h2><div className="mt-3 space-y-3">{scan.changes.filter((change) => change.type === "CONTENT_CHANGE").map((change) => <article key={change.id} className="border border-white/[.075] bg-[#0c0e12]"><div className="flex items-center justify-between border-b border-white/[.06] p-3"><p className="max-w-[75%] truncate text-[10px] text-[#979b93]">{change.scanPage.title || change.scanPage.url}</p><span className="text-[8px] tracking-widest text-[#c19374]">{change.riskImpact}</span></div><div className="grid text-[10px] leading-5 md:grid-cols-2"><div className="border-b border-white/[.06] p-4 md:border-b-0 md:border-r"><p className="mb-2 text-[8px] uppercase tracking-widest text-[#7e6868]">Before</p>{change.diff.removals?.slice(0, 3).map((line) => <p key={line} className="bg-[#b95f5f]/5 px-2 py-1 text-[#a98888]">− {line}</p>)}</div><div className="p-4"><p className="mb-2 text-[8px] uppercase tracking-widest text-[#657d70]">After</p>{change.diff.additions?.slice(0, 3).map((line) => <p key={line} className="bg-[#5f9d7c]/5 px-2 py-1 text-[#8fab99]">+ {line}</p>)}</div></div></article>)}</div></div>}</section>}
  </div>;
}

function safeHost(value: string) { try { return new URL(value).hostname; } catch { return value; } }

function scanProgressPercent(scan: Scan, progress: Progress) {
  if (scan.status === "COMPLETED" || progress.stage === "completed") return 100;
  const stageProgress: Record<string, number> = { queued: 2, discovering: 7, classifying: 68, evidence: 94, scoring: 97, failed: 0 };
  if (progress.stage === "crawling") {
    const total = Math.max(progress.stageTotal ?? 0, progress.pagesTotal, scan.pagesDiscovered);
    const processed = Math.max(progress.stageProcessed ?? 0, progress.pagesProcessed);
    return Math.round(12 + (total > 0 ? Math.min(1, processed / total) : 0) * 50);
  }
  if (progress.stage === "analyzing") {
    const total = progress.stageTotal ?? 0;
    const ratio = total > 0 ? Math.min(1, (progress.stageProcessed ?? 0) / total) : 0;
    return Math.round(72 + ratio * 20);
  }
  return stageProgress[progress.stage] ?? 0;
}

function formatElapsed(start: string, end?: string) {
  const seconds = Math.max(0, Math.round((new Date(end ?? Date.now()).getTime() - new Date(start).getTime()) / 1000));
  if (seconds < 60) return `${seconds}s`;
  const minutes = Math.floor(seconds / 60);
  return minutes < 60 ? `${minutes}m ${seconds % 60}s` : `${Math.floor(minutes / 60)}h ${minutes % 60}m`;
}

function formatUpdated(value: string) {
  const seconds = Math.max(0, Math.round((Date.now() - new Date(value).getTime()) / 1000));
  return seconds < 5 ? "just now" : seconds < 60 ? `${seconds}s ago` : `${Math.floor(seconds / 60)}m ago`;
}
