"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, BadgeCheck, Check, CheckCircle2, ChevronRight, Clock3, Copy, Download, ExternalLink, FileCheck2, FileSignature, Link2, LockKeyhole, Play, RefreshCw, Send, ShieldAlert, Upload } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState, type RefObject } from "react";
import { useRouter } from "next/navigation";
import { sentinelFetch } from "./client";
import { EmptyState, HealthRing, Severity, StatusIcon } from "./ui";
import { cn } from "@/lib/utils";
import { useSentinelRole } from "./auth-context";
import { STRIPE_CONNECT_COUNTRIES, stripeConnectCountryName } from "@/stripe/countries";
import { RelayIntegrationCard, type RelayIntegration } from "./relay-integration";
import { WooCommercePaymentsCard, type WooCommerceInstallationSummary } from "./woocommerce-payments-card";
import { portalActivationEligibility } from "@/merchant-portal/eligibility";
import { StripeEmbeddedOnboarding, type StripeEmbeddedSession } from "./stripe-embedded-onboarding";

type FindingEvidence = { id: string; kind: string; pageUrl: string; normalizedText?: string; evidenceSnippet?: string; storageKey?: string; metadata?: unknown; createdAt: string };
type Finding = { id: string; severity: string; confidence: number; status: string; category: string; title: string; description: string; url: string; detectedText?: string; reason: string; recommendedAction: string; lastDetectedAt: string; evidence: FindingEvidence[] };
type StripeRequirement = { key: string; label: string; status: string; awaitingActionFrom?: string; errorCodes?: string[] };
type StripeIntegration = { id: string; stripeAccountId: string; stripeEnvironment: string; accountApiVersion: string; displayStatus: string; cardPaymentsStatus?: string; payoutsStatus?: string; requirementsCurrentlyDue: StripeRequirement[]; requirementsEventuallyDue: StripeRequirement[]; requirementsPastDue: StripeRequirement[]; requirementsPendingVerification: StripeRequirement[]; futureRequirements: StripeRequirement[]; statusDetails: Array<{ capability: string; code: string; resolution?: string }>; disabledReason?: string; onboardingStartedAt?: string; onboardingCompletedAt?: string; lastSyncedAt?: string; createdAt: string; updatedAt: string };
type SignedAgreementRevision = { id: string; revision: number; originalName: string; sizeBytes: number; sha256: string; source: string; uploadedAt: string };
type AgreementState = { status: string; workflow?: string; invitationExpiresAt: string; invitationIssuedAt?: string | null; informationCertifiedAt?: string; contractIssuedAt?: string; signedUploadedAt?: string; signedOriginalName?: string; signedSizeBytes?: number; lockedAt?: string; termsVersion: string; signedRevisions?: SignedAgreementRevision[] };
type Merchant = { id: string; businessName: string; industry: string; country: string; legalCountry?: string; platformFeeBps?: number | null; businessDescription: string; status: string; isDemo: boolean; portalEnabled?: boolean; portalEnabledAt?: string | null; agreement?: AgreementState | null; stripeConnect?: StripeIntegration; stripeConnectAvailable?: boolean; wooCommerceRelay?: RelayIntegration; wooCommerceRelayAvailable?: boolean; wooCommerceInstallations?: WooCommerceInstallationSummary[]; wooCommercePaymentsAvailable?: boolean; sites: Array<{ id: string; hostname: string; normalizedUrl: string; lastScannedAt?: string }>; scans: Array<{ id: string; mode: string; status: string; progress?: unknown; createdAt: string; completedAt?: string; pagesProcessed: number; productsDetected: number; policiesDetected: number; findingsCreated: number; findingsResolved: number; scoreBefore?: number; scoreAfter?: number }>; healthScores: Array<{ total: number; createdAt: string; components: Array<{ key: string; label: string; score: number; deductions: unknown[] }> }>; findings: Finding[]; products: Array<{ id: string; name: string; sku?: string; currentPrice?: string; claims: unknown[]; lastSeenAt: string; snapshots: Array<{ data: unknown }> }>; policies: Array<{ id: string; type: string; coverage: string; url?: string }>; auditLogs: Array<{ id: string; action: string; targetType: string; createdAt: string; metadata: unknown }> };
const tabs = ["Overview", "Contract", "Findings", "Products", "Policies", "Scans", "Timeline", "Evidence", "Integrations"] as const;

export function MerchantDashboard({ merchantId, stripeReturn = "", openStripe = false }: { merchantId: string; stripeReturn?: string; openStripe?: boolean }) {
  const role = useSentinelRole(); const canEdit = ["OWNER", "ADMIN", "ANALYST"].includes(role); const canReview = ["OWNER", "ADMIN", "ANALYST", "REVIEWER"].includes(role); const canManageIntegrations = ["OWNER", "ADMIN"].includes(role); const canSelfServeStripe = ["OWNER", "ADMIN", "REVIEWER", "VIEWER"].includes(role);
  const [merchant, setMerchant] = useState<Merchant>(); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [tab, setTab] = useState<(typeof tabs)[number]>(stripeReturn || openStripe ? "Integrations" : "Overview"); const [starting, setStarting] = useState(false); const router = useRouter();
  const load = useCallback(async () => { setLoading(true); try { const data = await sentinelFetch<{ merchant: Merchant }>(`/api/sentinel/merchants/${merchantId}`); setMerchant(data.merchant); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load merchant"); } finally { setLoading(false); } }, [merchantId]);
  useEffect(() => { let active = true; sentinelFetch<{ merchant: Merchant }>(`/api/sentinel/merchants/${merchantId}`).then((data) => { if (active) { setMerchant(data.merchant); setError(""); } }).catch((cause: unknown) => { if (active) setError(cause instanceof Error ? cause.message : "Unable to load merchant"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [merchantId]);
  const counts = useMemo(() => merchant?.findings.reduce<Record<string, number>>((result, item) => { if (!["RESOLVED", "FALSE_POSITIVE", "IGNORED"].includes(item.status)) result[item.severity] = (result[item.severity] ?? 0) + 1; return result; }, {}) ?? {}, [merchant]);
  async function startScan() { if (!merchant) return; setStarting(true); setError(""); try { const data = await sentinelFetch<{ scan: { id: string } }>("/api/ai-scanner/scans", { method: "POST", body: JSON.stringify({ merchantId: merchant.id }) }); router.push(`/sentinel/scan/${data.scan.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to start AI scan"); setStarting(false); } }
  if (loading) return <MerchantSkeleton />;
  if (!merchant) return <div className="p-8"><EmptyState title="Merchant unavailable" detail={error || "This record could not be loaded."} /></div>;
  const score = merchant.healthScores[0]; const activeFindings = merchant.findings.filter((item) => !["RESOLVED", "FALSE_POSITIVE", "IGNORED"].includes(item.status)); const awaitingCustomer = merchant.agreement?.status === "INVITED" && !merchant.sites[0];
  return <div className="mx-auto w-full max-w-[1500px] px-4 py-6 sm:px-7 lg:px-10 lg:py-9">
    <Link href="/sentinel" className="inline-flex items-center gap-1.5 text-[10px] text-[#696d76] hover:text-[#b8bab5]"><ArrowLeft className="size-3" />Watchtower</Link>
    <header className="mt-5 flex flex-col gap-5 border-b border-white/[.07] pb-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-medium tracking-[-.04em] sm:text-3xl">{awaitingCustomer ? "Invitation pending" : merchant.businessName}</h1>{merchant.isDemo && <span className="rounded border border-[#797bec]/20 bg-[#797bec]/5 px-1.5 py-0.5 text-[8px] font-semibold tracking-widest text-[#8d8ff1]">DEMO</span>}</div><div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-[10px] text-[#686c75]">{awaitingCustomer ? <span>Waiting for the customer to complete their profile</span> : <><span>{merchant.industry}</span><span className="size-0.5 rounded-full bg-[#444850]" /><span>{merchant.country}</span>{merchant.sites[0] && <><span className="size-0.5 rounded-full bg-[#444850]" /><a href={merchant.sites[0].normalizedUrl} target="_blank" rel="noreferrer" className="flex items-center gap-1 hover:text-[#a7a9a5]">{merchant.sites[0].hostname}<ExternalLink className="size-2.5" /></a></>}</>}</div></div><div className="flex flex-wrap items-center gap-2"><button onClick={() => void load()} className="grid size-9 place-items-center rounded-md border border-white/[.09] text-[#777b84]" aria-label="Refresh merchant"><RefreshCw className="size-3.5" /></button>{!awaitingCustomer && <>{merchant.scans[0]?.completedAt && <a href={`/api/ai-scanner/scans/${merchant.scans[0].id}/report`} className="inline-flex h-9 items-center gap-2 rounded-md border border-white/[.1] px-3.5 text-[10px] text-[#c2c4bf] transition-colors hover:border-white/[.18] hover:bg-white/[.035]"><Download className="size-3" />Download report</a>}{canEdit && <button onClick={startScan} disabled={starting} className="inline-flex h-9 items-center gap-2 rounded-md bg-[#ecece8] px-4 text-[11px] font-medium text-black disabled:opacity-50"><Play className="size-3 fill-current" />{starting ? "Queueing…" : "Start AI scan"}</button>}</>}</div></header>
    {error && <p className="mt-4 border border-[#d17777]/20 bg-[#d17777]/5 p-3 text-xs text-[#d99595]">{error}</p>}
    <nav className="-mx-4 flex overflow-x-auto border-b border-white/[.07] px-4 sm:-mx-7 sm:px-7 lg:-mx-10 lg:px-10" aria-label="Merchant sections">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={cn("relative h-12 shrink-0 px-3 text-[10px] transition-colors", tab === item ? "text-[#e4e5e1] after:absolute after:inset-x-3 after:bottom-0 after:h-px after:bg-[#8588f2]" : "text-[#676b73] hover:text-[#aaa] ")}>{item}</button>)}</nav>
    {tab === "Overview" && <><PortalActivationPanel merchant={merchant} reload={load} canManage={canManageIntegrations} /><Overview merchant={merchant} score={score} counts={counts} activeFindings={activeFindings} setTab={setTab} /></>}
    {tab === "Contract" && <ContractPanel merchant={merchant} canManage={canEdit} canAdminister={canManageIntegrations} reload={load} />}
    {tab === "Findings" && <Findings findings={activeFindings} reload={load} canReview={canReview} />}
    {tab === "Products" && <Products merchant={merchant} />}
    {tab === "Policies" && <Policies merchant={merchant} />}
    {tab === "Scans" && <Scans merchant={merchant} />}
    {tab === "Timeline" && <Timeline merchant={merchant} />}
    {tab === "Evidence" && <Evidence findings={merchant.findings} />}
    {tab === "Integrations" && <Integrations merchant={merchant} canManage={canManageIntegrations} canSelfServeStripe={canSelfServeStripe} reload={load} setError={setError} stripeReturn={stripeReturn} />}
  </div>;
}

function Overview({ merchant, score, counts, activeFindings, setTab }: { merchant: Merchant; score?: Merchant["healthScores"][number]; counts: Record<string, number>; activeFindings: Finding[]; setTab: (tab: (typeof tabs)[number]) => void }) {
  const latest = merchant.scans[0];
  const readiness = (counts.CRITICAL ?? 0) > 0 ? "NOT_READY_CRITICAL_FINDINGS" : (counts.HIGH ?? 0) > 0 ? "NEEDS_REMEDIATION" : activeFindings.length > 0 ? "MANUAL_REVIEW_REQUIRED" : "READY_FOR_REVIEW";
  return <div className="mt-7 grid gap-7 xl:grid-cols-[1.3fr_.7fr]"><div><section className="border border-white/[.075] bg-[#0c0e12]"><div className="grid md:grid-cols-[220px_1fr]"><div className="flex items-center gap-5 border-b border-white/[.07] p-6 md:block md:border-b-0 md:border-r"><HealthRing value={score?.total ?? 0} /><div className="md:mt-4"><p className="text-[9px] uppercase tracking-[.14em] text-[#686c74]">AI Scanner score</p><p className="mt-1 text-xs text-[#c3c5c0]">{score ? score.total >= 85 ? "Strong observed posture" : score.total >= 65 ? "Review recommended" : "Attention required" : "Awaiting first AI scan"}</p><p className="mt-2 text-[9px] leading-4 text-[#555a62]">Transparent score: 0 is weakest, 100 strongest; unknown surfaces reserve points.</p><p className="mt-3 break-words font-mono text-[8px] tracking-[.08em] text-[#8588ef]">{readiness}</p></div></div><div className="grid grid-cols-2 sm:grid-cols-3"><Metric label="Monitoring" value={latest && !["AI_SCAN_FAILED", "AI_SCAN_INCOMPLETE", "COMPLETED", "CANCELLED"].includes(latest.status) ? "Scanning" : merchant.sites[0]?.lastScannedAt ? "Active" : "Pending"} /><Metric label="Critical" value={counts.CRITICAL ?? 0} /><Metric label="High" value={counts.HIGH ?? 0} /><Metric label="Pages opened" value={latest?.pagesProcessed ?? 0} /><Metric label="Products verified" value={merchant.products.length} /><Metric label="Luna findings" value={latest?.findingsCreated ?? 0} /></div></div></section>
      <AssessmentSummary latest={latest} activeFindings={activeFindings} />
      <section className="mt-7"><div className="flex items-end justify-between"><div><h2 className="text-sm font-medium">Priority findings</h2><p className="mt-1 text-[10px] text-[#636770]">Signals ordered for human review</p></div><button onClick={() => setTab("Findings")} className="text-[10px] text-[#898be9]">View all</button></div><div className="mt-3 border border-white/[.075] bg-[#0c0e12]">{activeFindings.length ? activeFindings.slice(0, 5).map((finding) => <div key={finding.id} className="grid gap-3 border-b border-white/[.06] p-4 last:border-0 sm:grid-cols-[80px_1fr_auto] sm:items-center"><Severity value={finding.severity} /><div><p className="text-xs text-[#d1d3ce]">{finding.title}</p><p className="mt-1 truncate text-[10px] text-[#60646d]">{new URL(finding.url).pathname} · {Math.round(finding.confidence * 100)}% confidence</p></div><ChevronRight className="hidden size-3.5 text-[#555962] sm:block" /></div>) : <EmptyState title="No open findings" detail="Open findings will appear here after a completed scan." />}</div></section>
    </div><aside><section className="border-t border-white/[.07] pt-4"><h2 className="text-sm font-medium">Score composition</h2><div className="mt-4 space-y-4">{score?.components.map((component) => <div key={component.key}><div className="flex justify-between text-[10px]"><span className="text-[#858991]">{component.label}</span><span className="tabular-nums text-[#d2d4cf]">{component.score}</span></div><div className="mt-2 h-1 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-[#777aea]" style={{ width: `${component.score}%` }} /></div><p className="mt-1 text-[9px] text-[#555962]">{component.deductions.length ? `${component.deductions.length} explained deduction${component.deductions.length === 1 ? "" : "s"}` : "No deductions"}</p></div>) ?? <p className="text-[10px] text-[#62666e]">Complete a scan to calculate each component.</p>}</div></section><section className="mt-8 border-t border-white/[.07] pt-4"><h2 className="text-sm font-medium">Recent scans</h2><div className="mt-3">{merchant.scans.slice(0, 5).map((scan) => <Link key={scan.id} href={`/sentinel/scan/${scan.id}`} className="flex items-center gap-2 border-b border-white/[.055] py-3"><StatusIcon status={scan.status} /><span className="text-[10px] text-[#858991]">{scan.mode}</span><span className="ml-auto text-[9px] text-[#5b6068]">{new Date(scan.createdAt).toLocaleDateString()}</span><ArrowRight className="size-3 text-[#555962]" /></Link>)}</div></section></aside></div>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="min-h-24 border-b border-r border-white/[.06] p-4"><p className="text-[9px] text-[#636770]">{label}</p><p className="mt-3 text-xl font-medium tracking-[-.04em]">{value}</p></div>; }
function progressNumber(progress: unknown, key: string) { return typeof progress === "object" && progress !== null && !Array.isArray(progress) && key in progress && typeof progress[key as keyof typeof progress] === "number" ? progress[key as keyof typeof progress] as number : 0; }
function progressArrayLength(progress: unknown, key: string) { return typeof progress === "object" && progress !== null && !Array.isArray(progress) && key in progress && Array.isArray(progress[key as keyof typeof progress]) ? (progress[key as keyof typeof progress] as unknown[]).length : 0; }
function AssessmentSummary({ latest, activeFindings }: { latest?: Merchant["scans"][number]; activeFindings: Finding[] }) { if (!latest || !["COMPLETED", "AI_SCAN_INCOMPLETE"].includes(latest.status)) return null; const visualPages = progressArrayLength(latest.progress, "pagesVisuallyReviewed"); const regions = progressNumber(latest.progress, "visualRegionsInspected"); const tools = progressNumber(latest.progress, "totalLunaToolCalls"); const checkout = progressArrayLength(latest.progress, "checkoutStatesInspected"); const documents = progressArrayLength(latest.progress, "documentsInspected"); return <section className="mt-7 border border-white/[.075] bg-[#0c0e12] p-5"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#777aea]">Luna investigation</p><p className="mt-3 text-xs leading-6 text-[#aeb1aa]">Luna opened {latest.pagesProcessed} public pages, visually reviewed {visualPages}, inspected {regions} rendered regions, and verified {latest.productsDetected} products. {activeFindings.length ? `${activeFindings.length} open evidence-backed finding${activeFindings.length === 1 ? " remains" : "s remain"} for review.` : "No material finding was produced from the retained evidence."}</p><p className="mt-2 text-[10px] leading-5 text-[#686c74]">Actual activity: {tools} Luna tool calls, {documents} documents, and {checkout} read-only checkout states. No configured limit is represented as a coverage percentage.</p><p className="mt-3 border-t border-white/[.06] pt-3 text-[9px] leading-4 text-[#555a62]">No finding means no material issue was observed in reviewed evidence. Unobserved surfaces remain unknown.</p></section>; }

function Findings({ findings, reload, canReview }: { findings: Finding[]; reload: () => Promise<void>; canReview: boolean }) { const [working, setWorking] = useState(""); async function decide(id: string, decision: string) { setWorking(id); await sentinelFetch(`/api/ai-scanner/findings/${id}`, { method: "PATCH", body: JSON.stringify({ decision }) }); await reload(); setWorking(""); } return <section className="mt-7"><h2 className="text-sm font-medium">Findings</h2><div className="mt-4 space-y-3">{findings.length ? findings.map((finding) => <details key={finding.id} className="group border border-white/[.075] bg-[#0c0e12]"><summary className="grid cursor-pointer list-none gap-3 p-4 sm:grid-cols-[80px_1fr_auto] sm:items-center"><Severity value={finding.severity} /><div><p className="text-xs text-[#d2d4cf]">{finding.title}</p><p className="mt-1 text-[10px] text-[#62666f]">{finding.category} · {Math.round(finding.confidence * 100)}% confidence · {finding.status.replaceAll("_", " ")}</p></div><ChevronRight className="size-3.5 text-[#5e626a] transition-transform group-open:rotate-90" /></summary><div className="border-t border-white/[.06] p-4 sm:p-5"><div className="grid gap-6 lg:grid-cols-2"><div><Label>What Luna observed</Label><p className="mt-2 text-xs leading-5 text-[#a9aca5]">{finding.description}</p><Label className="mt-5">Evidence-backed explanation</Label><p className="mt-2 text-xs leading-5 text-[#8c9098]">{finding.reason}</p></div><div><Label>Context-specific remediation</Label><p className="mt-2 text-xs leading-5 text-[#a9aca5]">{finding.recommendedAction}</p><FindingEvidencePanel finding={finding} /></div></div>{canReview && <div className="mt-5 flex flex-wrap gap-2 border-t border-white/[.06] pt-4"><button disabled={working === finding.id} onClick={() => void decide(finding.id, "CONFIRM")} className="h-8 rounded border border-white/[.09] px-3 text-[10px] text-[#aeb0ab]">Confirm</button><button disabled={working === finding.id} onClick={() => void decide(finding.id, "FALSE_POSITIVE")} className="h-8 rounded border border-white/[.09] px-3 text-[10px] text-[#aeb0ab]">False positive</button><button disabled={working === finding.id} onClick={() => void decide(finding.id, "ACCEPT_RISK")} className="h-8 rounded border border-white/[.09] px-3 text-[10px] text-[#aeb0ab]">Accept risk</button><button disabled={working === finding.id} onClick={() => void decide(finding.id, "RESOLVE")} className="h-8 rounded bg-[#e8e9e5] px-3 text-[10px] text-black">Resolve</button></div>}</div></details>) : <EmptyState title="No findings" detail="Luna creates findings only from validated retained first-party evidence." />}</div></section>; }
function evidenceRole(metadata: unknown, fallback: string) { return typeof metadata === "object" && metadata !== null && !Array.isArray(metadata) && "role" in metadata ? String(metadata.role).replaceAll("-", " ") : fallback; }
function FindingEvidencePanel({ finding }: { finding: Finding }) { const records = finding.evidence.filter((item) => item.kind === "TEXT").sort((left, right) => evidenceRole(left.metadata, "supporting") === "primary" ? -1 : evidenceRole(right.metadata, "supporting") === "primary" ? 1 : 0); return <div className="mt-5"><Label>Verifiable evidence</Label><div className="mt-3 space-y-2">{records.length ? records.map((item, index) => <div key={item.id} className="border border-white/[.065] bg-black/10 p-3"><p className="text-[8px] font-semibold uppercase tracking-[.13em] text-[#8588ef]">Evidence {String.fromCharCode(65 + index)} · {evidenceRole(item.metadata, index === 0 ? "primary" : "supporting")}</p>{item.evidenceSnippet && <blockquote className="mt-2 border-l border-[#8588ef] pl-3 font-mono text-[10px] leading-5 text-[#c4c6c2]">“{item.evidenceSnippet}”</blockquote>}<a href={item.pageUrl} target="_blank" rel="noreferrer" className="mt-2 block break-all text-[9px] text-[#71757d] hover:text-[#989aee]">{item.pageUrl}</a></div>) : <p className="text-[10px] text-[#61656d]">No text evidence was retained for this observation.</p>}</div><p className="mt-2 text-[9px] text-[#555a62]">{finding.evidence.length} immutable evidence record{finding.evidence.length === 1 ? "" : "s"}</p></div>; }
function Label({ children, className }: { children: React.ReactNode; className?: string }) { return <p className={cn("text-[9px] font-semibold uppercase tracking-[.13em] text-[#666b73]", className)}>{children}</p>; }
function productIntelligence(data: unknown) { if (typeof data !== "object" || data === null || Array.isArray(data) || !("intelligence" in data) || typeof data.intelligence !== "object" || data.intelligence === null || Array.isArray(data.intelligence)) return undefined; return data.intelligence as Record<string, unknown>; }
function Products({ merchant }: { merchant: Merchant }) { return <TableSection title="Product intelligence" columns={["Catalog name", "Canonical identity", "Suggested identifier", "Suggested SKU", "Price", "Claims"]} rows={merchant.products.map((product) => { const intelligence = productIntelligence(product.snapshots[0]?.data); return [product.name, typeof intelligence?.canonicalCompoundName === "string" ? intelligence.canonicalCompoundName : "Unresolved", typeof intelligence?.recommendedDisplayIdentifier === "string" ? intelligence.recommendedDisplayIdentifier : "—", typeof intelligence?.suggestedSku === "string" ? intelligence.suggestedSku : product.sku ?? "—", product.currentPrice ? `$${product.currentPrice}` : "—", String(product.claims.length)]; })} empty="No products have been classified yet." />; }
function Policies({ merchant }: { merchant: Merchant }) {
  const types = ["TERMS", "PRIVACY", "REFUND", "SHIPPING", "CONTACT", "RESEARCH_USE", "AGE", "PROMOTION"];
  const required = new Set(["TERMS", "PRIVACY", "REFUND", "SHIPPING", "CONTACT"]);
  return <section className="mt-7"><div><h2 className="text-sm font-medium">Policy coverage</h2><p className="mt-1 text-[10px] text-[#62666e]">Required coverage is separated from contextual controls.</p></div><div className="mt-4 grid border-l border-t border-white/[.07] sm:grid-cols-2 lg:grid-cols-4">{types.map((type) => {
    const policy = merchant.policies.find((item) => item.type === type); const found = policy?.coverage === "FOUND"; const notApplicable = policy?.coverage === "NOT_APPLICABLE"; const uncertain = policy?.coverage === "NEEDS_REVIEW"; const isRequired = required.has(type) && !notApplicable;
    const label = found ? "Found" : notApplicable ? "Not applicable to observed model" : uncertain ? "Needs review · incomplete scan" : isRequired ? "Missing" : "Not observed · contextual";
    return <div key={type} className="min-h-28 border-b border-r border-white/[.07] p-4"><div className="flex items-start justify-between gap-2"><p className="text-[9px] uppercase tracking-[.11em] text-[#62666e]">{type.replaceAll("_", " ")}</p><span className="text-[8px] uppercase tracking-[.1em] text-[#4f535b]">{notApplicable ? "N/A" : isRequired ? "Required" : "Contextual"}</span></div><p className="mt-4 flex items-center gap-2 text-[11px] text-[#b5b7b2]">{found ? <CheckCircle2 className="size-3.5 text-[#6fc39d]" /> : isRequired ? <ShieldAlert className="size-3.5 text-[#b9a46c]" /> : <span className="size-3.5 rounded-full border border-white/[.15]" />}{label}</p>{found && policy?.url && <a href={policy.url} target="_blank" rel="noreferrer" className="mt-2 block truncate text-[9px] text-[#6669c9] hover:text-[#9294ef]">{new URL(policy.url).pathname}</a>}</div>;
  })}</div></section>;
}
function Scans({ merchant }: { merchant: Merchant }) { return <TableSection title="Scan history" columns={["Type", "Started", "Pages", "Findings", "Score", "Status"]} rows={merchant.scans.map((scan) => [scan.mode, new Date(scan.createdAt).toLocaleString(), String(scan.pagesProcessed), `${scan.findingsCreated} new · ${scan.findingsResolved} resolved`, scan.scoreAfter === undefined ? "—" : `${scan.scoreBefore ?? "—"} → ${scan.scoreAfter}`, scan.status])} empty="No scans have been started." />; }
function Evidence({ findings }: { findings: Finding[] }) { const rows = findings.flatMap((finding) => finding.evidence.map((item) => [finding.title, item.kind, item.evidenceSnippet ?? "Captured page state", new Date(item.createdAt).toLocaleString()])); return <TableSection title="Evidence Vault" columns={["Finding", "Kind", "Evidence", "Captured"]} rows={rows} empty="Evidence records will appear after findings are detected." />; }
function Timeline({ merchant }: { merchant: Merchant }) { return <section className="mt-7"><h2 className="text-sm font-medium">Merchant timeline</h2><div className="mt-4 border-l border-white/[.08] pl-5">{merchant.auditLogs.length ? merchant.auditLogs.map((event) => <div key={event.id} className="relative border-b border-white/[.055] py-4 before:absolute before:-left-[25px] before:top-[19px] before:size-2 before:rounded-full before:border before:border-[#7d80eb] before:bg-[#0a0c0f]"><div className="flex items-center gap-3"><Clock3 className="size-3 text-[#646870]" /><p className="text-[11px] text-[#afb1ac]">{event.action.replaceAll(".", " ").replace(/\b\w/g, (letter) => letter.toUpperCase())}</p><time className="ml-auto text-[9px] text-[#555a62]">{new Date(event.createdAt).toLocaleString()}</time></div><p className="mt-1 pl-6 text-[9px] text-[#5f646c]">{event.targetType}</p></div>) : <EmptyState title="No activity yet" detail="Scan and review actions will be preserved here." />}</div></section>; }

function ContractPanel({ merchant, canManage, canAdminister, reload }: { merchant: Merchant; canManage: boolean; canAdminister: boolean; reload: () => Promise<void> }) {
  const agreement = merchant.agreement;
  const [working, setWorking] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [invitationUrl, setInvitationUrl] = useState("");
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState("");
  const fileInput = useRef<HTMLInputElement>(null);
  async function invitation() { setWorking(true); setError(""); try { const data = await sentinelFetch<{ invitationUrl: string }>(`/api/sentinel/merchants/${merchant.id}/agreement/invitation`, { method: "POST" }); setInvitationUrl(data.invitationUrl); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to create invitation"); } finally { setWorking(false); } }
  async function copy() { await navigator.clipboard.writeText(invitationUrl); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }
  async function uploadSigned(file: File | undefined) {
    if (!file || !agreement) return;
    if (agreement.status === "SIGNED_LOCKED" && !window.confirm("Upload this PDF as the new current signed agreement? The existing signed copy will remain preserved in revision history.")) { if (fileInput.current) fileInput.current.value = ""; return; }
    setUploading(true); setError("");
    try {
      const formData = new FormData(); formData.append("contract", file);
      await sentinelFetch(`/api/sentinel/merchants/${merchant.id}/agreement/signed`, { method: "POST", body: formData });
      await reload();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to upload the signed agreement"); }
    finally { setUploading(false); if (fileInput.current) fileInput.current.value = ""; }
  }
  if (!agreement) return <section className="mt-7 max-w-4xl border border-white/[.075] bg-[#0c0e12] p-6"><span className="grid size-11 place-items-center rounded-md border border-[#8588ef]/20 bg-[#8588ef]/[.05]"><FileSignature className="size-4 text-[#8d90f4]" /></span><h2 className="mt-5 text-base font-medium">Start contractual onboarding</h2><p className="mt-2 max-w-xl text-[11px] leading-5 text-[#777b84]">This merchant predates the contractual workflow. Create its private invitation without changing the monitoring record.</p>{canManage && <button onClick={() => void invitation()} disabled={working} className="mt-5 inline-flex h-10 items-center justify-center gap-2 rounded-md bg-[#ecece8] px-4 text-[10px] font-medium text-black disabled:opacity-50"><Send className="size-3" />{working ? "Creating…" : "Create onboarding invitation"}</button>}{invitationUrl && <div className="mt-4 flex items-center gap-2 rounded-md border border-white/[.08] bg-black/20 p-2"><p className="min-w-0 flex-1 truncate px-2 font-mono text-[9px] text-[#81858d]">{invitationUrl}</p><button onClick={() => void copy()} className="inline-flex h-8 items-center gap-2 rounded bg-white/[.08] px-3 text-[9px] text-white">{copied ? <Check className="size-3" /> : <Copy className="size-3" />}{copied ? "Copied" : "Copy"}</button></div>}{error && <p className="mt-3 text-[10px] text-[#d99595]">{error}</p>}</section>;
  if (agreement.status === "INVITED" && !agreement.invitationIssuedAt) return <section className="mt-7 max-w-4xl border border-white/[.075] bg-[#0c0e12] p-6"><div className="flex items-start justify-between gap-5"><span className="grid size-11 place-items-center rounded-md border border-[#8588ef]/20 bg-[#8588ef]/[.05]"><FileSignature className="size-4 text-[#8d90f4]" /></span><span className="rounded border border-white/[.08] px-2 py-1 font-mono text-[8px] tracking-[.1em] text-[#626771]">READY</span></div><h2 className="mt-5 text-base font-medium">Existing merchant ready for agreement</h2><p className="mt-2 max-w-2xl text-[11px] leading-5 text-[#777b84]">The account, monitoring and integrations remain active. Create a private customer link to prefill the existing business profile and collect only the signer, legal and contractual certification still required to issue the agreement.</p>{canManage && <button onClick={() => void invitation()} disabled={working} className="mt-5 inline-flex h-10 items-center justify-center gap-2 rounded-md bg-[#ecece8] px-4 text-[10px] font-medium text-black disabled:opacity-50"><Send className="size-3" />{working ? "Creating…" : "Create customer contract link"}</button>}{invitationUrl && <div className="mt-4 flex items-center gap-2 rounded-md border border-white/[.08] bg-black/20 p-2"><p className="min-w-0 flex-1 truncate px-2 font-mono text-[9px] text-[#81858d]">{invitationUrl}</p><button onClick={() => void copy()} className="inline-flex h-8 items-center gap-2 rounded bg-white/[.08] px-3 text-[9px] text-white">{copied ? <Check className="size-3" /> : <Copy className="size-3" />}{copied ? "Copied" : "Copy link"}</button></div>}{error && <p className="mt-3 text-[10px] text-[#d99595]">{error}</p>}</section>;
  const locked = agreement.status === "SIGNED_LOCKED";
  const completed = agreement.status !== "INVITED";
  const issued = ["CONTRACT_ISSUED", "SIGNED_LOCKED"].includes(agreement.status);
  const revisions = agreement.signedRevisions ?? [];
  const steps = [
    { label: "Customer link created", complete: Boolean(agreement.invitationIssuedAt), date: agreement.invitationIssuedAt ?? undefined, detail: locked ? "Link retired" : `Expires ${new Date(agreement.invitationExpiresAt).toLocaleDateString()}` },
    { label: "Contract details certified", complete: completed, date: agreement.informationCertifiedAt, detail: completed ? "Contract data is immutable" : "Existing profile prefilled · awaiting signer details" },
    { label: "Contract issued", complete: issued, date: agreement.contractIssuedAt, detail: issued ? `Terms ${agreement.termsVersion}` : "Generated after intake" },
    { label: "Signed & locked", complete: locked, date: agreement.signedUploadedAt, detail: locked ? `${revisions.length || 1} custody revision${(revisions.length || 1) === 1 ? "" : "s"}` : "Final custody step" },
  ];
  return <section className="mt-7 max-w-5xl"><div className="overflow-hidden border border-white/[.075] bg-[#0c0e12]"><div className="flex flex-col gap-5 border-b border-white/[.065] p-6 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-4"><span className={`grid size-11 shrink-0 place-items-center rounded-md border ${locked ? "border-[#6dccaa]/25 bg-[#6dccaa]/[.06]" : "border-[#8588ef]/20 bg-[#8588ef]/[.05]"}`}>{locked ? <LockKeyhole className="size-4 text-[#78d2af]" /> : <FileSignature className="size-4 text-[#8d90f4]" />}</span><div><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-[#696e77]">Agreement record</p><h2 className="mt-2 text-base font-medium">{locked ? "Signed agreement protected" : completed ? "Contract information certified" : "Existing account ready · signer details pending"}</h2><p className="mt-2 max-w-xl text-[11px] leading-5 text-[#777b84]">{locked ? "Every signed PDF and its integrity hash are retained. Owners and administrators can add a newer revision without deleting earlier custody copies." : completed ? "The customer certified their information. The issued agreement can now be downloaded, signed and returned by the customer or an administrator." : "The merchant account, monitoring and Stripe connection remain active. Its private link is prefilled with the existing ORBIT profile; the customer only needs to confirm the remaining legal and signer details."}</p></div></div><span className={`self-start rounded border px-2 py-1 font-mono text-[8px] tracking-[.1em] ${locked ? "border-[#6dccaa]/20 text-[#73cdaa]" : "border-white/[.08] text-[#626771]"}`}>{agreement.status}</span></div><div className="grid gap-px bg-white/[.06] sm:grid-cols-4">{steps.map((step, index) => <div key={step.label} className="bg-[#0c0e12] p-5"><div className="flex items-center gap-2"><span className={`grid size-5 place-items-center rounded-full border text-[8px] ${step.complete ? "border-[#6dccaa]/25 bg-[#6dccaa]/[.06] text-[#74d0ad]" : "border-white/[.1] text-[#555a62]"}`}>{step.complete ? <Check className="size-2.5" /> : index + 1}</span><p className="text-[10px] text-[#b1b3ae]">{step.label}</p></div><p className="mt-3 text-[8px] text-[#555a62]">{step.detail}</p>{step.date && <p className="mt-1 text-[8px] text-[#6d7179]">{new Date(step.date).toLocaleString()}</p>}</div>)}</div>
    {!locked && canManage && <div className="p-6"><div className="flex flex-col gap-3 sm:flex-row sm:flex-wrap"><button onClick={() => void invitation()} disabled={working} className="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-[#ecece8] px-4 text-[10px] font-medium text-black disabled:opacity-50"><Send className="size-3" />{working ? "Creating link…" : invitationUrl ? "Create replacement customer link" : completed ? "Create signing link" : "Create customer contract link"}</button>{completed && <a href={`/api/sentinel/merchants/${merchant.id}/agreement/contract`} className="inline-flex h-10 items-center justify-center gap-2 rounded-md border border-white/[.1] px-4 text-[10px] text-[#c2c4bf]"><Download className="size-3" />Download issued contract</a>}{issued && canAdminister && <SignedUploadButton inputRef={fileInput} uploading={uploading} label="Upload signed PDF" onFile={(file) => void uploadSigned(file)} />}</div>{invitationUrl && <div className="mt-4 flex items-center gap-2 rounded-md border border-white/[.08] bg-black/20 p-2"><p className="min-w-0 flex-1 truncate px-2 font-mono text-[9px] text-[#81858d]">{invitationUrl}</p><button onClick={() => void copy()} className="inline-flex h-8 items-center gap-2 rounded bg-white/[.08] px-3 text-[9px] text-white">{copied ? <Check className="size-3" /> : <Copy className="size-3" />}{copied ? "Copied" : "Copy customer link"}</button></div>}<p className="mt-3 text-[9px] leading-4 text-[#555a62]">Send the private link to the customer, or have an owner/administrator upload the completed signed PDF here. PDF only, maximum 15 MB.</p>{error && <p className="mt-3 text-[10px] text-[#d99595]">{error}</p>}</div>}
    {locked && <div className="p-6"><div className="flex flex-col gap-3 sm:flex-row sm:flex-wrap"><a href={`/api/sentinel/merchants/${merchant.id}/agreement/signed`} className="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-[#ecece8] px-4 text-[10px] font-medium text-black"><FileCheck2 className="size-3" />Download current signed agreement</a><a href={`/api/sentinel/merchants/${merchant.id}/agreement/contract`} className="inline-flex h-10 items-center justify-center gap-2 rounded-md border border-white/[.1] px-4 text-[10px] text-[#c2c4bf]"><Download className="size-3" />Download issued original</a>{canAdminister && <SignedUploadButton inputRef={fileInput} uploading={uploading} label="Upload updated signed PDF" onFile={(file) => void uploadSigned(file)} />}</div>{error && <p className="mt-3 text-[10px] text-[#d99595]">{error}</p>}</div>}
    {locked && revisions.length > 0 && <div className="border-t border-white/[.065] px-6 py-5"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#696e77]">Signed revision history</p><div className="mt-3 divide-y divide-white/[.055]">{revisions.map((revision) => <div key={revision.id} className="flex flex-col gap-2 py-3 sm:flex-row sm:items-center"><div className="min-w-0"><p className="truncate text-[10px] text-[#b8bab5]">Version {revision.revision} · {revision.originalName}</p><p className="mt-1 text-[8px] text-[#555a62]">{new Date(revision.uploadedAt).toLocaleString()} · {(revision.sizeBytes / 1_048_576).toFixed(2)} MB · {revision.source.toLowerCase()}</p></div><a href={`/api/sentinel/merchants/${merchant.id}/agreement/signed/${revision.id}`} className="inline-flex h-8 items-center justify-center gap-2 rounded border border-white/[.09] px-3 text-[9px] text-[#aeb0ab] sm:ml-auto"><Download className="size-3" />Download</a></div>)}</div></div>}
  </div></section>;
}

function SignedUploadButton({ inputRef, uploading, label, onFile }: { inputRef: RefObject<HTMLInputElement | null>; uploading: boolean; label: string; onFile: (file?: File) => void }) {
  return <label className={cn("inline-flex h-10 cursor-pointer items-center justify-center gap-2 rounded-md border border-[#8588ef]/25 bg-[#8588ef]/[.05] px-4 text-[10px] text-[#a9abf5]", uploading && "pointer-events-none opacity-50")}><Upload className="size-3" />{uploading ? "Uploading…" : label}<input ref={inputRef} type="file" accept="application/pdf,.pdf" className="sr-only" onChange={(event) => onFile(event.target.files?.[0])} disabled={uploading} /></label>;
}

const stripeStatusCopy: Record<string, { title: string; detail: string; tone: string }> = {
  NOT_CONNECTED: { title: "Not connected", detail: "Connect your Stripe account to begin business verification.", tone: "text-[#8b8f98]" },
  ONBOARDING: { title: "Onboarding required", detail: "Complete Stripe's business and identity verification process.", tone: "text-[#c8ad6b]" },
  ACTION_REQUIRED: { title: "Action required", detail: "Stripe requires additional information.", tone: "text-[#d39a72]" },
  IN_REVIEW: { title: "In review", detail: "Stripe is reviewing the submitted information.", tone: "text-[#8f91ef]" },
  RESTRICTED: { title: "Restricted", detail: "Stripe has restricted a required capability. Review the outstanding requirements.", tone: "text-[#d17777]" },
  ENABLED: { title: "Enabled", detail: "Stripe reports no current action required for the requested merchant capability.", tone: "text-[#6fc39d]" },
  UNKNOWN: { title: "Status unavailable", detail: "ORBIT could not determine a definitive Stripe verification state. Synchronize again or review Stripe.", tone: "text-[#8b8f98]" },
};

function Integrations(props: { merchant: Merchant; canManage: boolean; canSelfServeStripe: boolean; reload: () => Promise<void>; setError: (value: string) => void; stripeReturn: string }) {
  return <><StripeIntegration {...props} /><WooCommercePaymentsCard merchantId={props.merchant.id} installations={props.merchant.wooCommerceInstallations ?? []} environment={props.merchant.stripeConnect?.stripeEnvironment === "TEST" ? "test" : "live"} available={props.merchant.wooCommercePaymentsAvailable !== false} canManage={props.canManage} reload={props.reload} /><RelayIntegrationCard merchantId={props.merchant.id} merchantName={props.merchant.businessName} platformFeeBps={props.merchant.platformFeeBps} integration={props.merchant.wooCommerceRelay} available={props.merchant.wooCommerceRelayAvailable !== false} canManage={props.canManage} reload={props.reload} /></>;
}

function PortalActivationPanel({ merchant, reload, canManage }: { merchant: Merchant; reload: () => Promise<void>; canManage: boolean }) {
  const [working, setWorking] = useState(false);
  const [error, setError] = useState("");
  const eligibility = portalActivationEligibility({
    agreementStatus: merchant.agreement?.status,
    stripeDisplayStatus: merchant.stripeConnect?.displayStatus,
    cardPaymentsStatus: merchant.stripeConnect?.cardPaymentsStatus,
    payoutsStatus: merchant.stripeConnect?.payoutsStatus,
  });
  const effectiveAccess = Boolean(merchant.portalEnabled && eligibility.eligible);
  async function toggle() {
    setWorking(true); setError("");
    try {
      await sentinelFetch(`/api/sentinel/merchants/${merchant.id}`, { method: "PATCH", body: JSON.stringify({ portalEnabled: !merchant.portalEnabled }) });
      await reload();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update portal access"); }
    finally { setWorking(false); }
  }
  const title = effectiveAccess ? "Financial portal enabled" : merchant.portalEnabled ? "Portal access suspended" : eligibility.eligible ? "Ready for manual activation" : "Portal activation pending";
  const detail = effectiveAccess
    ? "Assigned merchant users can open the dashboard. Disabling access takes effect on their next request."
    : merchant.portalEnabled
      ? "A required account status is no longer active. Assigned users are blocked until every requirement is restored."
      : "Users cannot open the financial dashboard until an owner or administrator activates it here.";
  return <section className={`mt-7 border ${effectiveAccess ? "border-[#6dccaa]/20 bg-[#6dccaa]/[.035]" : "border-white/[.075] bg-[#0c0e12]"}`}><div className="flex flex-col gap-5 border-b border-white/[.06] p-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${effectiveAccess ? "bg-[#6dccaa] shadow-[0_0_12px_rgba(109,204,170,.45)]" : "bg-[#555a62]"}`} /><p className="text-[9px] font-semibold uppercase tracking-[.15em] text-[#737780]">Merchant Portal access</p></div><h2 className="mt-3 text-base font-medium">{title}</h2><p className="mt-2 max-w-2xl text-[10px] leading-5 text-[#6f737c]">{detail}</p></div>{canManage && <button onClick={() => void toggle()} disabled={working || (!merchant.portalEnabled && !eligibility.eligible)} className={`h-9 shrink-0 rounded-md px-4 text-[10px] font-medium disabled:cursor-not-allowed disabled:opacity-40 ${merchant.portalEnabled ? "border border-[#d17777]/20 text-[#d99595]" : "bg-[#ecece8] text-black"}`}>{working ? "Updating…" : merchant.portalEnabled ? "Disable portal" : "Activate portal"}</button>}</div><div className="grid gap-px bg-white/[.055] sm:grid-cols-2 lg:grid-cols-4">{eligibility.requirements.map((requirement) => <div key={requirement.key} className="flex items-start gap-2 bg-[#0c0e12] p-4"><span className={`mt-0.5 grid size-4 shrink-0 place-items-center rounded-full border ${requirement.complete ? "border-[#6dccaa]/30 bg-[#6dccaa]/[.06] text-[#74d0ad]" : "border-white/[.1] text-[#555a62]"}`}>{requirement.complete ? <Check className="size-2.5" /> : null}</span><p className={`text-[9px] leading-4 ${requirement.complete ? "text-[#aeb1aa]" : "text-[#62666e]"}`}>{requirement.label}</p></div>)}</div>{error && <p className="border-t border-[#d17777]/15 px-5 py-3 text-[10px] text-[#d99595]">{error}</p>}</section>;
}

function StripeIntegration({ merchant, canManage, canSelfServeStripe, reload, setError, stripeReturn }: { merchant: Merchant; canManage: boolean; canSelfServeStripe: boolean; reload: () => Promise<void>; setError: (value: string) => void; stripeReturn: string }) {
  const integration = merchant.stripeConnect; const [working, setWorking] = useState<"country" | "connect" | "onboarding" | "sync" | "">("");
  const [legalCountry, setLegalCountry] = useState(merchant.legalCountry ?? "");
  const [embeddedSession, setEmbeddedSession] = useState<StripeEmbeddedSession>();
  if (merchant.stripeConnectAvailable === false) return <section className="mt-7 max-w-4xl"><div className="border border-[#d39a72]/20 bg-[#0c0e12] p-6"><div className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-md border border-[#d39a72]/20 bg-[#d39a72]/[.04]"><ShieldAlert className="size-4 text-[#d39a72]" /></span><div><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-[#696e77]">Stripe Connect</p><h2 className="mt-2 text-base font-medium text-[#d39a72]">Integration setup required</h2><p className="mt-2 max-w-xl text-[11px] leading-5 text-[#777b84]">The Stripe Connect database migration has not been applied in this environment. Merchant monitoring remains available, but Stripe connection actions are disabled until an operator completes the migration.</p></div></div></div></section>;
  const status = stripeStatusCopy[integration?.displayStatus ?? "NOT_CONNECTED"] ?? stripeStatusCopy.UNKNOWN;
  const requirements = [...(integration?.requirementsPastDue ?? []), ...(integration?.requirementsCurrentlyDue ?? [])].filter((item, index, all) => all.findIndex((candidate) => candidate.key === item.key) === index);
  async function action(kind: "connect" | "onboarding" | "sync") {
    if (embeddedSession && kind !== "sync") return;
    setWorking(kind); setError("");
    try {
      if (kind === "sync") {
        await sentinelFetch(`/api/sentinel/merchants/${merchant.id}/stripe/sync`, { method: "POST" });
        await reload();
        return;
      }
      if (kind === "connect") await sentinelFetch(`/api/sentinel/merchants/${merchant.id}/stripe/connect`, { method: "POST" });
      const accountSession = await sentinelFetch<StripeEmbeddedSession>(`/api/sentinel/merchants/${merchant.id}/stripe/embedded-session`, { method: "POST" });
      setEmbeddedSession(accountSession);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Stripe Connect request failed"); }
    finally { setWorking(""); }
  }
  async function finishEmbeddedOnboarding() {
    setEmbeddedSession(undefined);
    setWorking("sync"); setError("");
    try {
      await sentinelFetch(`/api/sentinel/merchants/${merchant.id}/stripe/sync`, { method: "POST" });
      await reload();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to confirm Stripe verification status"); }
    finally { setWorking(""); }
  }
  async function saveLegalCountry() {
    if (!legalCountry) return;
    setWorking("country"); setError("");
    try {
      await sentinelFetch(`/api/sentinel/merchants/${merchant.id}`, { method: "PATCH", body: JSON.stringify({ legalCountry }) });
      await reload();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save the legal business country"); }
    finally { setWorking(""); }
  }
  return <section id="stripe-connect" className="mt-7 max-w-4xl"><div className="border border-white/[.075] bg-[#0c0e12]"><div className="flex flex-col gap-5 border-b border-white/[.065] p-5 sm:flex-row sm:items-start sm:justify-between sm:p-6"><div className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-md border border-white/[.09] bg-white/[.025]"><Link2 className="size-4 text-[#888bf2]" /></span><div><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-[#696e77]">Stripe Connect</p><h2 className={cn("mt-2 text-base font-medium", status.tone)}>{status.title}</h2><p className="mt-2 max-w-xl text-[11px] leading-5 text-[#777b84]">{status.detail}</p></div></div>{integration && <span className="self-start rounded border border-white/[.08] px-2 py-1 font-mono text-[8px] uppercase tracking-[.1em] text-[#626771]">{integration.stripeEnvironment} · {integration.accountApiVersion}</span>}</div>
    {stripeReturn === "1" && <div className="border-b border-[#777aea]/15 bg-[#777aea]/[.04] px-5 py-3 text-[10px] text-[#a3a5f4]">Returned from Stripe. The verification state shown below was retrieved directly from Stripe; returning does not by itself mean approval.</div>}
    {stripeReturn === "error" && <div className="border-b border-[#d17777]/15 bg-[#d17777]/[.04] px-5 py-3 text-[10px] text-[#d99595]">ORBIT could not synchronize the Stripe verification state. Use Sync Stripe status to try again.</div>}
    <div className="p-5 sm:p-6"><div className="mb-5 border border-white/[.065] p-4"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#777b84]">Legal business country</p><p className="mt-2 max-w-2xl text-[10px] leading-5 text-[#62666e]">This must be the country where the legal business or entity is registered. It is not inferred from IP address, website domain, customer location, or user profile.</p>{(integration && merchant.legalCountry) || !canManage ? <p className={cn("mt-3 text-[11px]", merchant.legalCountry ? "text-[#b8bab5]" : "text-[#d39a72]")}>{merchant.legalCountry ? `${stripeConnectCountryName(merchant.legalCountry) ?? merchant.legalCountry} (${merchant.legalCountry})` : "Not set"}{integration && merchant.legalCountry && <span className="ml-2 text-[9px] text-[#555a62]">Locked after connection</span>}</p> : <div className="mt-3 flex flex-col gap-2 sm:flex-row"><select aria-label="Legal business country" value={legalCountry} onChange={(event) => setLegalCountry(event.target.value)} className="h-9 min-w-64 rounded-md border border-white/[.1] bg-[#111319] px-3 text-[10px] text-white outline-none focus:border-[#7779ea]"><option value="">Select a country</option>{STRIPE_CONNECT_COUNTRIES.map((country) => <option key={country.code} value={country.code}>{country.name} ({country.code}){"preview" in country && country.preview ? " — preview" : ""}</option>)}</select><button onClick={() => void saveLegalCountry()} disabled={!legalCountry || legalCountry === merchant.legalCountry || Boolean(working)} className="h-9 rounded-md border border-white/[.1] px-3.5 text-[10px] text-[#c2c4bf] disabled:opacity-40">{working === "country" ? "Saving…" : "Save country"}</button></div>}</div>{integration ? <><div className="grid gap-px overflow-hidden border border-white/[.06] bg-white/[.06] sm:grid-cols-3"><StripeMetric label="Verification" value={status.title} /><StripeMetric label="Card payments capability" value={integration.cardPaymentsStatus ?? "Not reported"} /><StripeMetric label="Payouts capability" value={integration.payoutsStatus ?? "Not reported"} /></div>
      {(requirements.length > 0 || integration.requirementsPendingVerification.length > 0) && <div className="mt-5 border border-white/[.065] p-4"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#777b84]">Requirements</p>{requirements.length > 0 && <><p className="mt-3 text-[11px] text-[#b8bab5]">Stripe requires additional information:</p><ul className="mt-3 space-y-2">{requirements.map((requirement) => <li key={requirement.key} className="flex items-center gap-2 text-[10px] text-[#8b8f97]"><ShieldAlert className="size-3 text-[#b99a68]" />{requirement.label}{requirement.status === "past_due" && <span className="text-[#c47d7d]">Past due</span>}</li>)}</ul></>}{integration.requirementsPendingVerification.length > 0 && <p className="mt-3 flex items-center gap-2 text-[10px] text-[#8b8f97]"><BadgeCheck className="size-3 text-[#8588ef]" />{integration.requirementsPendingVerification.length} requirement{integration.requirementsPendingVerification.length === 1 ? "" : "s"} pending Stripe verification</p>}</div>}
      <div className="mt-5 flex flex-wrap items-center gap-2">{canSelfServeStripe && integration.displayStatus !== "ENABLED" && <button onClick={() => void action("onboarding")} disabled={Boolean(working) || Boolean(embeddedSession)} className="inline-flex h-9 items-center gap-2 rounded-md bg-[#ecece8] px-4 text-[10px] font-medium text-black disabled:opacity-50">{working === "onboarding" ? "Preparing secure form…" : integration.onboardingStartedAt ? "Continue Stripe verification" : "Complete Stripe verification"}</button>} {canSelfServeStripe && <button onClick={() => void action("sync")} disabled={Boolean(working) || Boolean(embeddedSession)} className="inline-flex h-9 items-center gap-2 rounded-md border border-white/[.1] px-3.5 text-[10px] text-[#c2c4bf] disabled:opacity-50"><RefreshCw className={cn("size-3", working === "sync" && "animate-spin")} />Sync Stripe status</button>} {!canSelfServeStripe && <p className="text-[10px] text-[#62666e]">Stripe verification actions are unavailable for this role.</p>}<span className="ml-auto text-[9px] text-[#555a62]">Last synchronized {integration.lastSyncedAt ? new Date(integration.lastSyncedAt).toLocaleString() : "never"}</span></div></> : <div><p className="text-[11px] leading-5 text-[#777b84]">Stripe securely collects legal, ownership, identity, tax, document, and bank information inside ORBIT. ORBIT does not receive or store those sensitive values.</p>{canSelfServeStripe ? <><button onClick={() => void action("connect")} disabled={!merchant.legalCountry || Boolean(working) || Boolean(embeddedSession)} className="mt-5 inline-flex h-9 items-center gap-2 rounded-md bg-[#ecece8] px-4 text-[10px] font-medium text-black disabled:opacity-50"><Link2 className="size-3" />{working === "connect" ? "Preparing secure form…" : "Start Stripe verification"}</button>{!merchant.legalCountry && <p className="mt-2 text-[10px] text-[#d39a72]">An administrator must set the legal business country before Stripe verification can begin.</p>}</> : <p className="mt-4 text-[10px] text-[#62666e]">Stripe verification actions are unavailable for this role.</p>}</div>}</div></div>{embeddedSession && <StripeEmbeddedOnboarding key={embeddedSession.expiresAt} merchantId={merchant.id} merchantName={merchant.businessName} session={embeddedSession} onExit={finishEmbeddedOnboarding} />}<p className="mt-3 text-[9px] leading-4 text-[#555a62]">Stripe is the source of truth for this integration. ORBIT does not approve or certify merchants, and AI Scanner scoring remains independent.</p></section>;
}
function StripeMetric({ label, value }: { label: string; value: string }) { return <div className="bg-[#0c0e12] p-4"><p className="text-[8px] uppercase tracking-[.12em] text-[#555a62]">{label}</p><p className="mt-2 text-[10px] capitalize text-[#b8bab5]">{value.replaceAll("_", " ").toLowerCase()}</p></div>; }
function TableSection({ title, columns, rows, empty }: { title: string; columns: string[]; rows: string[][]; empty: string }) { return <section className="mt-7"><h2 className="text-sm font-medium">{title}</h2><div className="mt-4 overflow-x-auto border border-white/[.075] bg-[#0c0e12]">{rows.length ? <table className="w-full min-w-[650px] text-left"><thead><tr className="border-b border-white/[.07]">{columns.map((column) => <th key={column} className="px-4 py-3 text-[9px] font-medium uppercase tracking-[.12em] text-[#5e626b]">{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-b border-white/[.055] last:border-0">{row.map((cell, cellIndex) => <td key={cellIndex} className="max-w-xs truncate px-4 py-3 text-[10px] text-[#959990]">{cell}</td>)}</tr>)}</tbody></table> : <EmptyState title={empty} detail="Run a scan to populate this section from observed website data." />}</div></section>; }
function MerchantSkeleton() { return <div className="space-y-5 p-8"><div className="h-8 w-56 animate-pulse rounded bg-white/[.05]" /><div className="h-48 animate-pulse rounded bg-white/[.035]" /><div className="h-64 animate-pulse rounded bg-white/[.025]" /></div>; }
