"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, ChevronRight, Clock3, Download, ExternalLink, Play, RefreshCw, ShieldAlert } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { sentinelFetch } from "./client";
import { EmptyState, HealthRing, Severity, StatusIcon } from "./ui";
import { cn } from "@/lib/utils";
import { useSentinelRole } from "./auth-context";

type FindingEvidence = { id: string; kind: string; pageUrl: string; normalizedText?: string; evidenceSnippet?: string; storageKey?: string; metadata?: unknown; createdAt: string };
type Finding = { id: string; severity: string; confidence: number; status: string; category: string; title: string; description: string; url: string; detectedText?: string; reason: string; recommendedAction: string; lastDetectedAt: string; evidence: FindingEvidence[] };
type Merchant = { id: string; businessName: string; industry: string; country: string; businessDescription: string; status: string; isDemo: boolean; sites: Array<{ id: string; hostname: string; normalizedUrl: string; lastScannedAt?: string }>; scans: Array<{ id: string; mode: string; status: string; progress?: unknown; createdAt: string; completedAt?: string; pagesProcessed: number; productsDetected: number; policiesDetected: number; findingsCreated: number; findingsResolved: number; scoreBefore?: number; scoreAfter?: number }>; healthScores: Array<{ total: number; createdAt: string; components: Array<{ key: string; label: string; score: number; deductions: unknown[] }> }>; findings: Finding[]; products: Array<{ id: string; name: string; sku?: string; currentPrice?: string; claims: unknown[]; lastSeenAt: string; snapshots: Array<{ data: unknown }> }>; policies: Array<{ id: string; type: string; coverage: string; url?: string }>; auditLogs: Array<{ id: string; action: string; targetType: string; createdAt: string; metadata: unknown }> };
const tabs = ["Overview", "Findings", "Products", "Policies", "Scans", "Timeline", "Evidence"] as const;

export function MerchantDashboard({ merchantId }: { merchantId: string }) {
  const role = useSentinelRole(); const canEdit = ["OWNER", "ADMIN", "ANALYST"].includes(role); const canReview = ["OWNER", "ADMIN", "ANALYST", "REVIEWER"].includes(role);
  const [merchant, setMerchant] = useState<Merchant>(); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [tab, setTab] = useState<(typeof tabs)[number]>("Overview"); const [starting, setStarting] = useState(false); const router = useRouter();
  const load = useCallback(async () => { setLoading(true); try { const data = await sentinelFetch<{ merchant: Merchant }>(`/api/sentinel/merchants/${merchantId}`); setMerchant(data.merchant); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load merchant"); } finally { setLoading(false); } }, [merchantId]);
  useEffect(() => { let active = true; sentinelFetch<{ merchant: Merchant }>(`/api/sentinel/merchants/${merchantId}`).then((data) => { if (active) { setMerchant(data.merchant); setError(""); } }).catch((cause: unknown) => { if (active) setError(cause instanceof Error ? cause.message : "Unable to load merchant"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [merchantId]);
  const counts = useMemo(() => merchant?.findings.reduce<Record<string, number>>((result, item) => { if (!["RESOLVED", "FALSE_POSITIVE", "IGNORED"].includes(item.status)) result[item.severity] = (result[item.severity] ?? 0) + 1; return result; }, {}) ?? {}, [merchant]);
  async function startScan() { if (!merchant) return; setStarting(true); setError(""); try { const data = await sentinelFetch<{ scan: { id: string } }>("/api/sentinel/scans", { method: "POST", body: JSON.stringify({ merchantId: merchant.id, mode: "FULL" }) }); router.push(`/sentinel/scan/${data.scan.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to start scan"); setStarting(false); } }
  if (loading) return <MerchantSkeleton />;
  if (!merchant) return <div className="p-8"><EmptyState title="Merchant unavailable" detail={error || "This record could not be loaded."} /></div>;
  const score = merchant.healthScores[0]; const activeFindings = merchant.findings.filter((item) => !["RESOLVED", "FALSE_POSITIVE", "IGNORED"].includes(item.status));
  return <div className="mx-auto w-full max-w-[1500px] px-4 py-6 sm:px-7 lg:px-10 lg:py-9">
    <Link href="/sentinel" className="inline-flex items-center gap-1.5 text-[10px] text-[#696d76] hover:text-[#b8bab5]"><ArrowLeft className="size-3" />Watchtower</Link>
    <header className="mt-5 flex flex-col gap-5 border-b border-white/[.07] pb-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-medium tracking-[-.04em] sm:text-3xl">{merchant.businessName}</h1>{merchant.isDemo && <span className="rounded border border-[#797bec]/20 bg-[#797bec]/5 px-1.5 py-0.5 text-[8px] font-semibold tracking-widest text-[#8d8ff1]">DEMO</span>}</div><div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-[10px] text-[#686c75]"><span>{merchant.industry}</span><span className="size-0.5 rounded-full bg-[#444850]" /><span>{merchant.country}</span>{merchant.sites[0] && <><span className="size-0.5 rounded-full bg-[#444850]" /><a href={merchant.sites[0].normalizedUrl} target="_blank" rel="noreferrer" className="flex items-center gap-1 hover:text-[#a7a9a5]">{merchant.sites[0].hostname}<ExternalLink className="size-2.5" /></a></>}</div></div><div className="flex flex-wrap items-center gap-2"><button onClick={() => void load()} className="grid size-9 place-items-center rounded-md border border-white/[.09] text-[#777b84]" aria-label="Refresh merchant"><RefreshCw className="size-3.5" /></button><a href={`/api/sentinel/merchants/${merchant.id}/report/pdf`} className="inline-flex h-9 items-center gap-2 rounded-md border border-white/[.1] px-3.5 text-[10px] text-[#c2c4bf] transition-colors hover:border-white/[.18] hover:bg-white/[.035]"><Download className="size-3" />Download report</a>{canEdit && <button onClick={startScan} disabled={starting} className="inline-flex h-9 items-center gap-2 rounded-md bg-[#ecece8] px-4 text-[11px] font-medium text-black disabled:opacity-50"><Play className="size-3 fill-current" />{starting ? "Queueing…" : "Start full scan"}</button>}</div></header>
    {error && <p className="mt-4 border border-[#d17777]/20 bg-[#d17777]/5 p-3 text-xs text-[#d99595]">{error}</p>}
    <nav className="-mx-4 flex overflow-x-auto border-b border-white/[.07] px-4 sm:-mx-7 sm:px-7 lg:-mx-10 lg:px-10" aria-label="Merchant sections">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={cn("relative h-12 shrink-0 px-3 text-[10px] transition-colors", tab === item ? "text-[#e4e5e1] after:absolute after:inset-x-3 after:bottom-0 after:h-px after:bg-[#8588f2]" : "text-[#676b73] hover:text-[#aaa] ")}>{item}</button>)}</nav>
    {tab === "Overview" && <Overview merchant={merchant} score={score} counts={counts} activeFindings={activeFindings} setTab={setTab} />}
    {tab === "Findings" && <Findings findings={merchant.findings} reload={load} canReview={canReview} />}
    {tab === "Products" && <Products merchant={merchant} />}
    {tab === "Policies" && <Policies merchant={merchant} />}
    {tab === "Scans" && <Scans merchant={merchant} />}
    {tab === "Timeline" && <Timeline merchant={merchant} />}
    {tab === "Evidence" && <Evidence findings={merchant.findings} />}
  </div>;
}

function Overview({ merchant, score, counts, activeFindings, setTab }: { merchant: Merchant; score?: Merchant["healthScores"][number]; counts: Record<string, number>; activeFindings: Finding[]; setTab: (tab: (typeof tabs)[number]) => void }) {
  const latest = merchant.scans[0];
  const readiness = (counts.CRITICAL ?? 0) > 0 ? "NOT_READY_CRITICAL_FINDINGS" : (counts.HIGH ?? 0) > 0 ? "NEEDS_REMEDIATION" : activeFindings.length > 0 ? "MANUAL_REVIEW_REQUIRED" : "READY_FOR_REVIEW";
  return <div className="mt-7 grid gap-7 xl:grid-cols-[1.3fr_.7fr]"><div><section className="border border-white/[.075] bg-[#0c0e12]"><div className="grid md:grid-cols-[220px_1fr]"><div className="flex items-center gap-5 border-b border-white/[.07] p-6 md:block md:border-b-0 md:border-r"><HealthRing value={score?.total ?? 0} /><div className="md:mt-4"><p className="text-[9px] uppercase tracking-[.14em] text-[#686c74]">ORBIT Health</p><p className="mt-1 text-xs text-[#c3c5c0]">{score ? score.total >= 85 ? "Healthy" : score.total >= 65 ? "Review recommended" : "Attention required" : "Awaiting first scan"}</p><p className="mt-2 text-[9px] leading-4 text-[#555a62]">Internal score: 0 is weakest, 100 is strongest.</p><p className="mt-3 break-words font-mono text-[8px] tracking-[.08em] text-[#8588ef]">{readiness}</p></div></div><div className="grid grid-cols-2 sm:grid-cols-3"><Metric label="Monitoring" value={latest && !["FAILED", "COMPLETED"].includes(latest.status) ? "Scanning" : merchant.sites[0]?.lastScannedAt ? "Active" : "Pending"} /><Metric label="Critical" value={counts.CRITICAL ?? 0} /><Metric label="High" value={counts.HIGH ?? 0} /><Metric label="Pages" value={latest?.pagesProcessed ?? 0} /><Metric label="Products" value={merchant.products.length} /><Metric label="Policies" value={merchant.policies.filter((policy) => policy.coverage === "FOUND").length} /></div></div></section>
      <AssessmentSummary latest={latest} activeFindings={activeFindings} />
      <section className="mt-7"><div className="flex items-end justify-between"><div><h2 className="text-sm font-medium">Priority findings</h2><p className="mt-1 text-[10px] text-[#636770]">Signals ordered for human review</p></div><button onClick={() => setTab("Findings")} className="text-[10px] text-[#898be9]">View all</button></div><div className="mt-3 border border-white/[.075] bg-[#0c0e12]">{activeFindings.length ? activeFindings.slice(0, 5).map((finding) => <div key={finding.id} className="grid gap-3 border-b border-white/[.06] p-4 last:border-0 sm:grid-cols-[80px_1fr_auto] sm:items-center"><Severity value={finding.severity} /><div><p className="text-xs text-[#d1d3ce]">{finding.title}</p><p className="mt-1 truncate text-[10px] text-[#60646d]">{new URL(finding.url).pathname} · {Math.round(finding.confidence * 100)}% confidence</p></div><ChevronRight className="hidden size-3.5 text-[#555962] sm:block" /></div>) : <EmptyState title="No open findings" detail="Open findings will appear here after a completed scan." />}</div></section>
    </div><aside><section className="border-t border-white/[.07] pt-4"><h2 className="text-sm font-medium">Score composition</h2><div className="mt-4 space-y-4">{score?.components.map((component) => <div key={component.key}><div className="flex justify-between text-[10px]"><span className="text-[#858991]">{component.label}</span><span className="tabular-nums text-[#d2d4cf]">{component.score}</span></div><div className="mt-2 h-1 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-[#777aea]" style={{ width: `${component.score}%` }} /></div><p className="mt-1 text-[9px] text-[#555962]">{component.deductions.length ? `${component.deductions.length} explained deduction${component.deductions.length === 1 ? "" : "s"}` : "No deductions"}</p></div>) ?? <p className="text-[10px] text-[#62666e]">Complete a scan to calculate each component.</p>}</div></section><section className="mt-8 border-t border-white/[.07] pt-4"><h2 className="text-sm font-medium">Recent scans</h2><div className="mt-3">{merchant.scans.slice(0, 5).map((scan) => <Link key={scan.id} href={`/sentinel/scan/${scan.id}`} className="flex items-center gap-2 border-b border-white/[.055] py-3"><StatusIcon status={scan.status} /><span className="text-[10px] text-[#858991]">{scan.mode}</span><span className="ml-auto text-[9px] text-[#5b6068]">{new Date(scan.createdAt).toLocaleDateString()}</span><ArrowRight className="size-3 text-[#555962]" /></Link>)}</div></section></aside></div>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="min-h-24 border-b border-r border-white/[.06] p-4"><p className="text-[9px] text-[#636770]">{label}</p><p className="mt-3 text-xl font-medium tracking-[-.04em]">{value}</p></div>; }
function progressNumber(progress: unknown, key: string) { return typeof progress === "object" && progress !== null && !Array.isArray(progress) && key in progress && typeof progress[key as keyof typeof progress] === "number" ? progress[key as keyof typeof progress] as number : 0; }
function AssessmentSummary({ latest, activeFindings }: { latest?: Merchant["scans"][number]; activeFindings: Finding[] }) { if (!latest || latest.status !== "COMPLETED") return null; const coverage = progressNumber(latest.progress, "scanCoveragePercent"); const certificates = progressNumber(latest.progress, "certificatesDiscovered"); const certificatesAnalyzed = progressNumber(latest.progress, "certificatesAnalyzed"); const checkout = progressNumber(latest.progress, "checkoutFlowsInspected"); const disclaimers = progressNumber(latest.progress, "disclaimerPagesObserved"); const restrictionPages = progressNumber(latest.progress, "researchRestrictionPagesObserved"); const researchProducts = progressNumber(latest.progress, "researchCoveredProducts"); return <section className="mt-7 border border-white/[.075] bg-[#0c0e12] p-5"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#777aea]">What needs attention</p><p className="mt-3 text-xs leading-6 text-[#aeb1aa]">ORBIT reviewed {latest.pagesProcessed} successfully processed public pages and mapped {latest.productsDetected} product pages within the discovered scan boundary. {activeFindings.length ? `${activeFindings.length} open evidence-backed observation${activeFindings.length === 1 ? " remains" : "s remain"} for human review.` : "No material open finding was produced from the evidence reviewed."}</p><p className="mt-3 text-[10px] leading-5 text-[#686c74]">Observed controls: {restrictionPages} page{restrictionPages === 1 ? "" : "s"} contained explicit use restrictions, including {disclaimers} identifiable disclaimer page{disclaimers === 1 ? "" : "s"}; {researchProducts} mapped product page{researchProducts === 1 ? "" : "s"} carried recognizable research-use language.</p><p className="mt-2 text-[10px] leading-5 text-[#686c74]">Observed coverage: {coverage}%. {checkout ? `${checkout} public cart or checkout view${checkout === 1 ? " was" : "s were"} inspected.` : "A public pre-payment checkout flow was not reached, so checkout controls remain unassessed."} {certificates ? `${certificates} certificate link${certificates === 1 ? " was" : "s were"} discovered; ${certificatesAnalyzed} received deep document analysis.` : "No certificate link was discovered in the scanned pages."}</p><p className="mt-3 border-t border-white/[.06] pt-3 text-[9px] leading-4 text-[#555a62]">No finding means no material issue was observed in the reviewed evidence. It does not mean every possible page, image, document or private flow was verified.</p></section>; }

function Findings({ findings, reload, canReview }: { findings: Finding[]; reload: () => Promise<void>; canReview: boolean }) { const [working, setWorking] = useState(""); async function decide(id: string, decision: string) { setWorking(id); await sentinelFetch(`/api/sentinel/findings/${id}`, { method: "PATCH", body: JSON.stringify({ decision }) }); await reload(); setWorking(""); } return <section className="mt-7"><h2 className="text-sm font-medium">Findings</h2><div className="mt-4 space-y-3">{findings.length ? findings.map((finding) => <details key={finding.id} className="group border border-white/[.075] bg-[#0c0e12]"><summary className="grid cursor-pointer list-none gap-3 p-4 sm:grid-cols-[80px_1fr_auto] sm:items-center"><Severity value={finding.severity} /><div><p className="text-xs text-[#d2d4cf]">{finding.title}</p><p className="mt-1 text-[10px] text-[#62666f]">{finding.category} · {Math.round(finding.confidence * 100)}% confidence · {finding.status.replaceAll("_", " ")}</p></div><ChevronRight className="size-3.5 text-[#5e626a] transition-transform group-open:rotate-90" /></summary><div className="border-t border-white/[.06] p-4 sm:p-5"><div className="grid gap-6 lg:grid-cols-2"><div><Label>What was detected</Label><p className="mt-2 text-xs leading-5 text-[#a9aca5]">{finding.description}</p><Label className="mt-5">Why ORBIT flagged this</Label><p className="mt-2 text-xs leading-5 text-[#8c9098]">{finding.reason}</p></div><div><Label>Recommended action</Label><p className="mt-2 text-xs leading-5 text-[#a9aca5]">{finding.recommendedAction}</p><FindingEvidencePanel finding={finding} /></div></div>{canReview && <div className="mt-5 flex flex-wrap gap-2 border-t border-white/[.06] pt-4"><button disabled={working === finding.id} onClick={() => void decide(finding.id, "CONFIRM")} className="h-8 rounded border border-white/[.09] px-3 text-[10px] text-[#aeb0ab]">Confirm</button><button disabled={working === finding.id} onClick={() => void decide(finding.id, "FALSE_POSITIVE")} className="h-8 rounded border border-white/[.09] px-3 text-[10px] text-[#aeb0ab]">False positive</button><button disabled={working === finding.id} onClick={() => void decide(finding.id, "ACCEPT_RISK")} className="h-8 rounded border border-white/[.09] px-3 text-[10px] text-[#aeb0ab]">Accept risk</button><button disabled={working === finding.id} onClick={() => void decide(finding.id, "RESOLVE")} className="h-8 rounded bg-[#e8e9e5] px-3 text-[10px] text-black">Resolve</button></div>}</div></details>) : <EmptyState title="No findings" detail="Findings are created from explainable rules and contextual analysis after a scan." />}</div></section>; }
function evidenceRole(metadata: unknown, fallback: string) { return typeof metadata === "object" && metadata !== null && !Array.isArray(metadata) && "role" in metadata ? String(metadata.role).replaceAll("-", " ") : fallback; }
function FindingEvidencePanel({ finding }: { finding: Finding }) { const records = finding.evidence.filter((item) => item.kind === "TEXT").sort((left, right) => evidenceRole(left.metadata, "supporting") === "primary" ? -1 : evidenceRole(right.metadata, "supporting") === "primary" ? 1 : 0); return <div className="mt-5"><Label>Verifiable evidence</Label><div className="mt-3 space-y-2">{records.length ? records.map((item, index) => <div key={item.id} className="border border-white/[.065] bg-black/10 p-3"><p className="text-[8px] font-semibold uppercase tracking-[.13em] text-[#8588ef]">Evidence {String.fromCharCode(65 + index)} · {evidenceRole(item.metadata, index === 0 ? "primary" : "supporting")}</p>{item.evidenceSnippet && <blockquote className="mt-2 border-l border-[#8588ef] pl-3 font-mono text-[10px] leading-5 text-[#c4c6c2]">“{item.evidenceSnippet}”</blockquote>}<a href={item.pageUrl} target="_blank" rel="noreferrer" className="mt-2 block break-all text-[9px] text-[#71757d] hover:text-[#989aee]">{item.pageUrl}</a></div>) : <p className="text-[10px] text-[#61656d]">No text evidence was retained for this observation.</p>}</div><p className="mt-2 text-[9px] text-[#555a62]">{finding.evidence.length} immutable evidence record{finding.evidence.length === 1 ? "" : "s"}</p></div>; }
function Label({ children, className }: { children: React.ReactNode; className?: string }) { return <p className={cn("text-[9px] font-semibold uppercase tracking-[.13em] text-[#666b73]", className)}>{children}</p>; }
function productIntelligence(data: unknown) { if (typeof data !== "object" || data === null || Array.isArray(data) || !("intelligence" in data) || typeof data.intelligence !== "object" || data.intelligence === null || Array.isArray(data.intelligence)) return undefined; return data.intelligence as Record<string, unknown>; }
function Products({ merchant }: { merchant: Merchant }) { return <TableSection title="Product intelligence" columns={["Catalog name", "Canonical identity", "Suggested identifier", "Suggested SKU", "Price", "Claims"]} rows={merchant.products.map((product) => { const intelligence = productIntelligence(product.snapshots[0]?.data); return [product.name, typeof intelligence?.canonicalCompoundName === "string" ? intelligence.canonicalCompoundName : "Unresolved", typeof intelligence?.recommendedDisplayIdentifier === "string" ? intelligence.recommendedDisplayIdentifier : "—", typeof intelligence?.suggestedSku === "string" ? intelligence.suggestedSku : product.sku ?? "—", product.currentPrice ? `$${product.currentPrice}` : "—", String(product.claims.length)]; })} empty="No products have been classified yet." />; }
function Policies({ merchant }: { merchant: Merchant }) {
  const types = ["TERMS", "PRIVACY", "REFUND", "SHIPPING", "CONTACT", "RESEARCH_USE", "AGE", "PROMOTION"];
  const required = new Set(["TERMS", "PRIVACY", "REFUND", "SHIPPING", "CONTACT"]);
  return <section className="mt-7"><div><h2 className="text-sm font-medium">Policy coverage</h2><p className="mt-1 text-[10px] text-[#62666e]">Required coverage is separated from contextual controls.</p></div><div className="mt-4 grid border-l border-t border-white/[.07] sm:grid-cols-2 lg:grid-cols-4">{types.map((type) => {
    const policy = merchant.policies.find((item) => item.type === type); const found = policy?.coverage === "FOUND"; const isRequired = required.has(type);
    const label = found ? "Found" : isRequired ? "Missing" : "Not observed · contextual";
    return <div key={type} className="min-h-28 border-b border-r border-white/[.07] p-4"><div className="flex items-start justify-between gap-2"><p className="text-[9px] uppercase tracking-[.11em] text-[#62666e]">{type.replaceAll("_", " ")}</p><span className="text-[8px] uppercase tracking-[.1em] text-[#4f535b]">{isRequired ? "Required" : "Contextual"}</span></div><p className="mt-4 flex items-center gap-2 text-[11px] text-[#b5b7b2]">{found ? <CheckCircle2 className="size-3.5 text-[#6fc39d]" /> : isRequired ? <ShieldAlert className="size-3.5 text-[#b9a46c]" /> : <span className="size-3.5 rounded-full border border-white/[.15]" />}{label}</p>{found && policy?.url && <a href={policy.url} target="_blank" rel="noreferrer" className="mt-2 block truncate text-[9px] text-[#6669c9] hover:text-[#9294ef]">{new URL(policy.url).pathname}</a>}</div>;
  })}</div></section>;
}
function Scans({ merchant }: { merchant: Merchant }) { return <TableSection title="Scan history" columns={["Type", "Started", "Pages", "Findings", "Score", "Status"]} rows={merchant.scans.map((scan) => [scan.mode, new Date(scan.createdAt).toLocaleString(), String(scan.pagesProcessed), `${scan.findingsCreated} new · ${scan.findingsResolved} resolved`, scan.scoreAfter === undefined ? "—" : `${scan.scoreBefore ?? "—"} → ${scan.scoreAfter}`, scan.status])} empty="No scans have been started." />; }
function Evidence({ findings }: { findings: Finding[] }) { const rows = findings.flatMap((finding) => finding.evidence.map((item) => [finding.title, item.kind, item.evidenceSnippet ?? "Captured page state", new Date(item.createdAt).toLocaleString()])); return <TableSection title="Evidence Vault" columns={["Finding", "Kind", "Evidence", "Captured"]} rows={rows} empty="Evidence records will appear after findings are detected." />; }
function Timeline({ merchant }: { merchant: Merchant }) { return <section className="mt-7"><h2 className="text-sm font-medium">Merchant timeline</h2><div className="mt-4 border-l border-white/[.08] pl-5">{merchant.auditLogs.length ? merchant.auditLogs.map((event) => <div key={event.id} className="relative border-b border-white/[.055] py-4 before:absolute before:-left-[25px] before:top-[19px] before:size-2 before:rounded-full before:border before:border-[#7d80eb] before:bg-[#0a0c0f]"><div className="flex items-center gap-3"><Clock3 className="size-3 text-[#646870]" /><p className="text-[11px] text-[#afb1ac]">{event.action.replaceAll(".", " ").replace(/\b\w/g, (letter) => letter.toUpperCase())}</p><time className="ml-auto text-[9px] text-[#555a62]">{new Date(event.createdAt).toLocaleString()}</time></div><p className="mt-1 pl-6 text-[9px] text-[#5f646c]">{event.targetType}</p></div>) : <EmptyState title="No activity yet" detail="Scan and review actions will be preserved here." />}</div></section>; }
function TableSection({ title, columns, rows, empty }: { title: string; columns: string[]; rows: string[][]; empty: string }) { return <section className="mt-7"><h2 className="text-sm font-medium">{title}</h2><div className="mt-4 overflow-x-auto border border-white/[.075] bg-[#0c0e12]">{rows.length ? <table className="w-full min-w-[650px] text-left"><thead><tr className="border-b border-white/[.07]">{columns.map((column) => <th key={column} className="px-4 py-3 text-[9px] font-medium uppercase tracking-[.12em] text-[#5e626b]">{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-b border-white/[.055] last:border-0">{row.map((cell, cellIndex) => <td key={cellIndex} className="max-w-xs truncate px-4 py-3 text-[10px] text-[#959990]">{cell}</td>)}</tr>)}</tbody></table> : <EmptyState title={empty} detail="Run a scan to populate this section from observed website data." />}</div></section>; }
function MerchantSkeleton() { return <div className="space-y-5 p-8"><div className="h-8 w-56 animate-pulse rounded bg-white/[.05]" /><div className="h-48 animate-pulse rounded bg-white/[.035]" /><div className="h-64 animate-pulse rounded bg-white/[.025]" /></div>; }
