import Link from "next/link";
import { ArrowLeft, Download, FileSpreadsheet, Landmark, ReceiptText } from "lucide-react";
import { notFound } from "next/navigation";
import { StatementActions } from "@/components/merchant-portal/statement-actions";
import { getPortalContext } from "@/merchant-portal/access";
import { formatMinor } from "@/statements/calculation";
import { getAccessibleMerchantStatement } from "@/statements/data";
import { getServerEnv } from "@/sentinel/config";

const day = (date: Date) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: getServerEnv().STATEMENT_TIMEZONE }).format(date);
const timestamp = (date: Date | null) => date ? new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: getServerEnv().STATEMENT_TIMEZONE }).format(date) : "—";

export default async function StatementPage({ params }: { params: Promise<{ statementId: string }> }) {
  const [{ merchants }, route] = await Promise.all([getPortalContext(), params]);
  const statement = await getAccessibleMerchantStatement(merchants.map((item) => item.id), route.statementId);
  if (!statement) notFound();
  const merchant = merchants.find((item) => item.id === statement.merchantId);
  if (!merchant) notFound();
  const money = (value: bigint) => formatMinor(value, statement.currency);
  const summary: Array<[string, bigint, "positive" | "negative" | "neutral"]> = [
    ["Gross payments", statement.grossPaymentsMinor, "positive"], ["Refunds", -statement.refundsMinor, "negative"], ["Disputes", -statement.disputesMinor, "negative"], ["ORBIT fees", -statement.orbitFeesMinor, "negative"], ["Processing fees", -statement.processingFeesMinor, "negative"], ["Adjustments", statement.adjustmentsMinor, "neutral"], ["Net activity", statement.netActivityMinor, "positive"], ["Payouts", -statement.payoutsMinor, "neutral"], ["Ending balance", statement.closingBalanceMinor, "positive"],
  ];
  return <div className="mx-auto w-full max-w-[1460px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10">
    <Link href="/dashboard/statements" className="inline-flex items-center gap-2 text-[10px] text-[#888e99]"><ArrowLeft className="size-3.5" />All statements</Link>
    <header className="mt-6 overflow-hidden rounded-[26px] border border-white/[.08] bg-[#0c0e15]"><div className="h-1.5 bg-[#6d5ce7]" /><div className="flex flex-col gap-7 p-6 sm:p-9 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[15px] font-semibold tracking-[-.02em]">ORBIT</p><p className="mt-1 text-[8px] uppercase tracking-[.16em] text-[#686e7a]">Monthly statement</p><h1 className="mt-8 text-[28px] font-semibold tracking-[-.05em] sm:text-[38px]">{statement.merchant.agreement?.legalName ?? statement.merchant.businessName}</h1><p className="mt-3 text-[11px] text-[#7d838f]">{day(statement.periodStart)} – {day(new Date(statement.periodEnd.getTime() - 1))} · {statement.currency}</p></div><div className="grid gap-4 text-[9px] sm:grid-cols-2 lg:min-w-[470px]"><div><p className="uppercase tracking-[.12em] text-[#5f6571]">Statement ID</p><p className="mt-1.5 font-mono text-[#b2a7fa]">{statement.publicId}</p></div><div><p className="uppercase tracking-[.12em] text-[#5f6571]">Generated at</p><p className="mt-1.5 text-[#bdc0c7]">{timestamp(statement.generatedAt)}</p></div><div><p className="uppercase tracking-[.12em] text-[#5f6571]">Status</p><p className="mt-1.5 text-[#78d3b2]">{statement.status}</p></div><div><p className="uppercase tracking-[.12em] text-[#5f6571]">Email</p><p className="mt-1.5 text-[#bdc0c7]">{statement.emailStatus}{statement.emailSentAt ? ` · ${timestamp(statement.emailSentAt)}` : ""}</p></div></div></div></header>
    <div className="mt-4 flex flex-wrap gap-2"><Link href={`/api/portal/statements/${statement.publicId}/pdf`} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#6d5ce7] px-4 text-[10px] font-semibold text-white"><Download className="size-3.5" />Download PDF</Link><Link href={`/api/portal/statements/${statement.publicId}/csv`} className="inline-flex h-10 items-center gap-2 rounded-xl border border-white/[.1] px-4 text-[10px] font-semibold text-[#d8dae0]"><FileSpreadsheet className="size-3.5" />Download CSV</Link><StatementActions publicId={statement.publicId} recipient={statement.merchant.agreement?.primaryContactEmail ?? null} canEmail={merchant.canManageStatements} /></div>
    <section className="mt-8"><div className="flex items-center gap-2"><Landmark className="size-4 text-[#9182f0]" /><h2 className="text-[17px] font-semibold">Account summary</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{summary.map(([label, amount, tone]) => <article key={label} className={`rounded-[20px] border p-5 ${label === "Ending balance" ? "border-[#7868e8]/30 bg-[#7868e8]/[.09]" : "border-white/[.075] bg-[#0b0d13]"}`}><p className="text-[8px] font-semibold uppercase tracking-[.12em] text-[#727884]">{label}</p><p className={`mt-4 text-[24px] font-semibold tabular-nums ${tone === "negative" ? "text-[#d9a07d]" : tone === "positive" ? "text-white" : "text-[#bdc0c8]"}`}>{money(amount)}</p></article>)}</div>
      <div className="mt-4 rounded-[20px] border border-white/[.075] bg-[#0b0d13] p-5 text-[10px] text-[#858b96]"><div className="flex flex-wrap items-center gap-3"><span>Opening <b className="text-[#d9dbe0]">{money(statement.openingBalanceMinor)}</b></span><span>+</span><span>Net activity <b className="text-[#d9dbe0]">{money(statement.netActivityMinor)}</b></span><span>−</span><span>Payouts <b className="text-[#d9dbe0]">{money(statement.payoutsMinor)}</b></span><span>=</span><span>Closing <b className="text-[#8fdfc1]">{money(statement.closingBalanceMinor)}</b></span></div></div>
    </section>
    <div className="mt-8 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><section className="overflow-hidden rounded-[24px] border border-white/[.075] bg-[#0b0d13]"><div className="border-b border-white/[.07] px-6 py-5"><div className="flex items-center gap-2"><ReceiptText className="size-4 text-[#9182f0]" /><h2 className="text-[16px] font-semibold">Payment activity</h2></div><p className="mt-2 text-[9px] text-[#6e7480]">{statement.paymentCount} payments · {statement.refundCount} refunds · {statement.disputeCount} disputes</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-white/[.06]">{["Date", "Reference", "Type", "Gross", "Fees", "Net"].map((item) => <th key={item} className="px-4 py-3 text-[8px] uppercase text-[#626874] first:pl-6">{item}</th>)}</tr></thead><tbody>{statement.lineItems.filter((item) => item.type !== "PAYOUT").map((item) => <tr key={item.id} className="border-b border-white/[.05] last:border-0"><td className="py-4 pl-6 pr-4 text-[9px] text-[#7c828e]">{day(item.occurredAt)}</td><td className="px-4 font-mono text-[8px] text-[#9b8ff0]">{item.reference ?? item.externalId}</td><td className="px-4 text-[8px] text-[#9297a1]">{item.type}</td><td className="px-4 text-[9px] tabular-nums text-[#cfd2d8]">{money(item.amountMinor)}</td><td className="px-4 text-[9px] tabular-nums text-[#999eaa]">{money(item.processingFeeMinor + item.orbitFeeMinor)}</td><td className="px-4 text-[9px] font-semibold tabular-nums text-white">{money(item.netMinor)}</td></tr>)}</tbody></table>{!statement.lineItems.length && <p className="p-8 text-center text-[10px] text-[#6f7581]">No ledger activity in this period.</p>}</div></section>
      <div className="grid content-start gap-5"><section className="rounded-[24px] border border-white/[.075] bg-[#0b0d13] p-6"><h2 className="text-[16px] font-semibold">Fees</h2><div className="mt-5 space-y-4 text-[10px]"><div className="flex justify-between"><span className="text-[#808692]">ORBIT fees</span><span className="tabular-nums">{money(statement.orbitFeesMinor)}</span></div><div className="flex justify-between"><span className="text-[#808692]">Processing fees</span><span className="tabular-nums">{money(statement.processingFeesMinor)}</span></div></div></section><section className="rounded-[24px] border border-white/[.075] bg-[#0b0d13] p-6"><h2 className="text-[16px] font-semibold">Payout activity</h2><p className="mt-2 text-[9px] text-[#6f7581]">Total {money(statement.payoutsMinor)}</p><div className="mt-4 space-y-3">{statement.payouts.map((payout) => <div key={payout.id} className="border-t border-white/[.06] pt-3 text-[9px]"><div className="flex justify-between"><span className="font-mono text-[#998cee]">{payout.externalId}</span><span className="font-semibold">{money(payout.amountMinor)}</span></div><div className="mt-1 flex justify-between text-[#6f7581]"><span>{day(payout.initiatedAt)}{payout.arrivalAt ? ` → ${day(payout.arrivalAt)}` : ""}</span><span>{payout.status.replaceAll("_", " ")}</span></div>{payout.destinationSummary && <p className="mt-1 text-[#646a76]">{payout.destinationSummary}</p>}</div>)}{!statement.payouts.length && <p className="text-[9px] text-[#6f7581]">No payouts were initiated during this period.</p>}</div></section></div></div>
    <p className="mt-7 text-[9px] leading-5 text-[#656b77]">This statement summarizes payment activity recorded through ORBIT for the stated period. It is not a bank statement and does not constitute tax advice or an official tax form.</p>
  </div>;
}
