import type { Metadata } from "next";
import Link from "next/link";
import { AlertTriangle, ArrowLeft, BadgeDollarSign, CalendarClock, CheckCircle2, CircleOff, CreditCard, Landmark, Mail, MapPin, ReceiptText, RotateCcw, ShieldAlert, Sparkles, UserRound, XCircle } from "lucide-react";
import { notFound } from "next/navigation";
import { CopyButton } from "@/components/merchant-portal/copy-button";
import { getPortalContext } from "@/merchant-portal/access";
import { getMerchantPayment } from "@/merchant-portal/data";
import { formatMoney, formatPortalDate, formatPortalDateTime } from "@/merchant-portal/format";

export const metadata: Metadata = { title: "Payment details", robots: { index: false, follow: false } };

export default async function PaymentDetailPage({ params }: { params: Promise<{ paymentId: string }> }) {
  const [{ merchant }, { paymentId }] = await Promise.all([getPortalContext(), params]);
  if (!merchant) notFound();
  const payment = await getMerchantPayment(merchant.id, decodeURIComponent(paymentId));
  if (!payment) notFound();
  const failed = payment.displayStatus === "Failed";
  const processingFee = payment.processingFeeMinor;
  const totalFee = processingFee === null ? null : payment.platformFeeMinor + processingFee;
  const refundedLabel = payment.refundAmountMinor >= payment.amountMinor ? "Fully refunded" : payment.refundAmountMinor > 0 ? "Partially refunded" : "No refunds";
  const timeline = [
    { label: "Payment created", date: payment.createdAt, detail: `ORBIT ${payment.source.toLowerCase()} record`, failed: false },
    ...(payment.succeededAt ? [{ label: "Payment approved", date: payment.succeededAt, detail: "Verified by ORBIT Payment", failed: false }] : []),
    ...(failed ? [{ label: "Payment not approved", date: payment.createdAt, detail: payment.failureReason ?? "The payment was declined", failed: true }] : []),
    ...(payment.fundsAvailableOn ? [{ label: "Funds available", date: payment.fundsAvailableOn, detail: "Confirmed balance availability", failed: false }] : []),
  ];

  return <div className="mx-auto w-full max-w-[1320px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10">
    <Link href="/dashboard/payments" className="inline-flex items-center gap-1.5 text-[10px] font-medium text-[#777d89] transition hover:text-white"><ArrowLeft className="size-3.5" />Payments</Link>
    <header className="mt-6 flex flex-col gap-5 border-b border-white/[.07] pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.14em] text-[#a99cff]"><Sparkles className="size-3.5" />ORBIT Payment detail</p><div className="mt-3 flex flex-wrap items-center gap-3"><h1 className="text-[36px] font-semibold tracking-[-.055em] text-white sm:text-[46px]">{formatMoney(payment.amountMinor, payment.currency)}</h1><ResultBadge status={payment.displayStatus} /></div><p className="mt-3 text-[11px] text-[#8a909b]">Order #{payment.orderId} · {formatPortalDateTime(payment.createdAt)} UTC</p></div><CopyButton value={payment.publicId} label="Copy payment ID" /></header>

    {failed && <section className="mt-6 flex flex-col gap-4 rounded-[22px] border border-[#e17b91]/20 bg-[radial-gradient(circle_at_90%_0%,rgba(225,123,145,.12),transparent_38%),#111017] p-5 sm:flex-row sm:items-center"><span className="grid size-11 shrink-0 place-items-center rounded-2xl border border-[#e17b91]/20 bg-[#e17b91]/[.08] text-[#e7a0af]"><XCircle className="size-5" /></span><div className="min-w-0 flex-1"><p className="text-[9px] font-semibold uppercase tracking-[.13em] text-[#c67d8d]">Why it failed</p><h2 className="mt-2 text-[16px] font-semibold text-white">{payment.failureReason ?? "Payment was not approved"}</h2><p className="mt-1 text-[9px] text-[#777d89]">Processor code: {payment.failureCode ?? "not provided"}</p></div></section>}

    <div className="mt-6 grid gap-5 lg:grid-cols-[1.18fr_.82fr]">
      <div className="space-y-5">
        <section className="relative overflow-hidden rounded-[24px] border border-[#8f7dff]/25 bg-[radial-gradient(circle_at_90%_0%,rgba(128,99,255,.22),transparent_38%),#11131b] p-6 shadow-[0_24px_65px_rgba(0,0,0,.22)] sm:p-8"><div className="flex items-center justify-between"><p className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.14em] text-[#a99cff]"><BadgeDollarSign className="size-3.5" />Payment breakdown</p><span className="text-[8px] text-[#646a76]">{payment.currency.toUpperCase()}</span></div><div className="mt-7 space-y-4"><BreakdownRow label="Gross amount" value={formatMoney(payment.amountMinor, payment.currency)} /><BreakdownRow label="ORBIT fee" value={`−${formatMoney(payment.platformFeeMinor, payment.currency)}`} muted /><BreakdownRow label="Processing fee" value={processingFee === null ? "—" : `−${formatMoney(processingFee, payment.currency)}`} muted /><div className="border-t border-white/[.1] pt-5"><BreakdownRow label="Total fees" value={totalFee === null ? "—" : `−${formatMoney(totalFee, payment.currency)}`} accent /></div><div className="border-t border-white/[.1] pt-5"><BreakdownRow label="Net amount" value={payment.netMinor === null ? "—" : formatMoney(payment.netMinor, payment.currency)} strong /></div></div>{processingFee === null && <p className="mt-5 flex items-start gap-2 text-[8px] leading-4 text-[#747a86]"><AlertTriangle className="mt-0.5 size-3 shrink-0 text-[#c6a568]" />The processing fee is unavailable, so ORBIT does not estimate total fees or net.</p>}</section>

        <section className="rounded-[22px] border border-white/[.075] bg-[#0b0d13] p-6 sm:p-7"><p className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.14em] text-[#777d89]"><ReceiptText className="size-3.5 text-[#9182f0]" />Payment information</p><div className="mt-5 divide-y divide-white/[.06]"><InfoRow label="ORBIT Payment ID" value={payment.publicId} copy /><InfoRow label="Order ID" value={payment.orderId} /><InfoRow label="Source" value={payment.source.charAt(0) + payment.source.slice(1).toLowerCase()} /><InfoRow label="Created" value={`${formatPortalDateTime(payment.createdAt)} UTC`} /><InfoRow label="Currency" value={payment.currency.toUpperCase()} /><InfoRow label="Result" value={payment.displayStatus} /><InfoRow label="Processor reference" value={payment.stripePaymentIntentId ?? "—"} copy={Boolean(payment.stripePaymentIntentId)} /><InfoRow label="Charge reference" value={payment.chargeId ?? "—"} copy={Boolean(payment.chargeId)} /></div></section>

        <section className="rounded-[22px] border border-white/[.075] bg-[#0b0d13] p-6 sm:p-7"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#777d89]">Payment timeline</p><div className="mt-6">{timeline.map((event, index) => <div key={`${event.label}-${index}`} className="grid grid-cols-[22px_1fr] gap-3"><div className="flex flex-col items-center"><span className={`mt-0.5 size-2.5 rounded-full border-[3px] bg-[#0b0d13] ${event.failed ? "border-[#d77d91]" : "border-[#8172eb]"}`} />{index < timeline.length - 1 && <span className="min-h-14 w-px flex-1 bg-white/[.08]" />}</div><div className="pb-6"><p className="text-[11px] font-medium text-[#d5d7dd]">{event.label}</p><p className="mt-1 text-[8px] text-[#777d89]">{formatPortalDateTime(event.date)} UTC</p><p className="mt-1 text-[8px] text-[#5f6571]">{event.detail}</p></div></div>)}</div></section>
      </div>

      <aside className="space-y-5">
        <DetailCard icon={<CreditCard className="size-4" />} label="Payment method"><h2 className="mt-3 text-[16px] font-semibold capitalize text-white">{payment.methodBrand ? `${payment.methodBrand}${payment.methodLast4 ? ` •••• ${payment.methodLast4}` : ""}` : "Method unavailable"}</h2><p className="mt-1 text-[9px] capitalize text-[#777d89]">{payment.methodType ?? "Payment method"}</p></DetailCard>
        <DetailCard icon={<UserRound className="size-4" />} label="Customer">{payment.customerName || payment.customerEmail || payment.billingCountry ? <div className="mt-3 space-y-2">{payment.customerName && <p className="text-[13px] font-medium text-white">{payment.customerName}</p>}{payment.customerEmail && <p className="flex items-center gap-2 break-all text-[9px] text-[#9297a2]"><Mail className="size-3 shrink-0 text-[#9182f0]" />{payment.customerEmail}</p>}{payment.billingCountry && <p className="flex items-center gap-2 text-[9px] text-[#9297a2]"><MapPin className="size-3 shrink-0 text-[#9182f0]" />{payment.billingCountry}</p>}</div> : <p className="mt-3 text-[10px] text-[#777d89]">No customer details available</p>}</DetailCard>
        <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2"><DetailCard icon={<RotateCcw className="size-4" />} label="Refund"><p className="mt-3 text-[12px] font-semibold text-white">{refundedLabel}</p>{payment.refundAmountMinor > 0 && <p className="mt-1 text-[9px] text-[#9297a2]">{formatMoney(payment.refundAmountMinor, payment.currency)}</p>}</DetailCard><DetailCard icon={payment.dispute ? <ShieldAlert className="size-4" /> : <CircleOff className="size-4" />} label="Dispute"><p className="mt-3 text-[12px] font-semibold text-white">{payment.dispute ? "Dispute open" : "No dispute"}</p>{payment.dispute && <p className="mt-1 text-[9px] text-[#d897a6]">{formatMoney(payment.dispute.amountMinor, payment.currency)} · {payment.dispute.status.replaceAll("_", " ")}</p>}</DetailCard></div>
        {payment.payout ? <Link href={`/dashboard/payouts/${payment.payout.id}`} className="block rounded-[22px] border border-[#8f7dff]/20 bg-[#8f7dff]/[.06] p-6 transition hover:border-[#8f7dff]/35"><div className="flex items-center gap-2 text-[#a99cff]"><Landmark className="size-4" /><p className="text-[9px] font-semibold uppercase tracking-[.13em]">Included in transfer</p></div><p className="mt-4 text-[24px] font-semibold text-white">{formatMoney(payment.payout.amountMinor, payment.payout.currency)}</p><p className="mt-2 text-[9px] text-[#777d89]">{payment.payout.status === "paid" ? "Paid" : "Expected"} {formatPortalDate(payment.payout.arrivalDate)} · {payment.payout.destination}</p></Link> : <DetailCard icon={<CalendarClock className="size-4" />} label="Balance availability">{payment.fundsAvailableOn ? <><p className="mt-3 text-[13px] font-semibold text-white">{formatPortalDate(payment.fundsAvailableOn)}</p><p className="mt-1 text-[8px] text-[#777d89]">Confirmed processing availability date</p></> : <p className="mt-3 text-[10px] text-[#777d89]">No confirmed date yet</p>}</DetailCard>}
      </aside>
    </div>
  </div>;
}

function ResultBadge({ status }: { status: string }) { const failed = status === "Failed"; const pending = status === "Pending"; const Icon = failed ? XCircle : pending ? CalendarClock : CheckCircle2; return <span className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-2 text-[8px] font-semibold ${failed ? "border-[#e17b91]/20 bg-[#e17b91]/[.07] text-[#e7a0af]" : pending ? "border-[#d4ae68]/20 bg-[#d4ae68]/[.07] text-[#d7b978]" : "border-[#5bd1a4]/20 bg-[#5bd1a4]/[.07] text-[#7edab7]"}`}><Icon className="size-3" />{status}</span>; }
function BreakdownRow({ label, value, muted, strong, accent }: { label: string; value: string; muted?: boolean; strong?: boolean; accent?: boolean }) { return <div className="flex items-center justify-between gap-4"><span className={`${strong ? "text-[13px] font-semibold text-white" : "text-[10px]"} ${muted ? "text-[#858b97]" : accent ? "text-[#a99cff]" : "text-[#cdd0d7]"}`}>{label}</span><span className={`${strong ? "text-[24px] font-semibold text-white" : "text-[12px] font-medium"} ${accent ? "text-[#b7acff]" : ""} tabular-nums`}>{value}</span></div>; }
function InfoRow({ label, value, copy }: { label: string; value: string; copy?: boolean }) { return <div className="flex min-h-12 items-center gap-4 py-2"><span className="w-36 shrink-0 text-[9px] text-[#777d89]">{label}</span><span className="min-w-0 flex-1 break-all text-right font-mono text-[9px] text-[#b9bdc6] sm:text-[10px]">{value}</span>{copy && value !== "—" && <CopyButton value={value} label="Copy" />}</div>; }
function DetailCard({ icon, label, children }: { icon: React.ReactNode; label: string; children: React.ReactNode }) { return <section className="rounded-[22px] border border-white/[.075] bg-[#0b0d13] p-6"><div className="flex items-center gap-2 text-[#9182f0]">{icon}<p className="text-[9px] font-semibold uppercase tracking-[.13em] text-[#777d89]">{label}</p></div>{children}</section>; }
