import Link from "next/link";
import { ArrowRight, BadgeDollarSign, Building2, CalendarClock, CircleDollarSign, Landmark, Layers3 } from "lucide-react";
import { MerchantPortalLink } from "./merchant-portal-link";
import { VolumeChart } from "./volume-chart";
import type { getAdminPortfolioOverview } from "@/merchant-portal/data";
import { formatMoney, formatPortalDate, formatPortalDateTime, relativeUpdatedAt } from "@/merchant-portal/format";

type Portfolio = Awaited<ReturnType<typeof getAdminPortfolioOverview>>;

export function AdminPortfolio({ portfolio }: { portfolio: Portfolio }) {
  const today = portfolio.periods[0];
  const available = portfolio.available.amountMinor === null ? "—" : formatMoney(portfolio.available.amountMinor, portfolio.currency);
  const pending = portfolio.pending.amountMinor === null ? "—" : formatMoney(portfolio.pending.amountMinor, portfolio.currency);
  return <div className="mx-auto w-full max-w-[1540px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-[#9b8cff]"><Layers3 className="size-3.5" /><p className="text-[10px] font-semibold uppercase tracking-[.15em]">Private admin portfolio</p></div><h1 className="mt-3 text-[30px] font-semibold tracking-[-.055em] text-white sm:text-[38px]">Everything happening across ORBIT.</h1><p className="mt-2 max-w-2xl text-[11px] leading-5 text-[#858a96]">All brands, payments, ORBIT revenue, balances and upcoming payouts. This consolidated view is available only to owners and administrators.</p></div><p className="text-[9px] text-[#646975]">Updated {relativeUpdatedAt(portfolio.updatedAt)}</p></header>

    <section className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <AdminMetric icon={<CircleDollarSign className="size-4" />} label="Gross sales today" value={formatMoney(today.grossMinor, portfolio.currency)} detail={`${today.payments} successful payments`} featured />
      <AdminMetric icon={<BadgeDollarSign className="size-4" />} label="ORBIT revenue today" value={formatMoney(today.orbitRevenueMinor, portfolio.currency)} detail="Platform fees earned today" />
      <AdminMetric icon={<Landmark className="size-4" />} label="Ready to pay out" value={available} detail={`${portfolio.liveMerchantCount} live Stripe account${portfolio.liveMerchantCount === 1 ? "" : "s"}`} />
      <AdminMetric icon={<CalendarClock className="size-4" />} label="Processing + upcoming" value={pending} detail={portfolio.nextPayoutTotalMinor > 0 ? `${formatMoney(portfolio.nextPayoutTotalMinor, portfolio.currency)} already scheduled` : "No scheduled payout reported"} />
    </section>

    <section className="mt-8 grid grid-cols-2 overflow-hidden rounded-2xl border border-white/[.07] bg-[#0c0e14] md:grid-cols-4">{portfolio.periods.map((period) => <div key={period.key} className="border-b border-r border-white/[.06] p-5 last:border-r-0 md:border-b-0"><p className="text-[8px] font-semibold uppercase tracking-[.14em] text-[#666b77]">{period.label}</p><p className="mt-3 text-[19px] font-semibold tracking-[-.04em] text-[#f0f0f4]">{formatMoney(period.grossMinor, portfolio.currency)}</p><p className="mt-1 text-[9px] text-[#6e7380]">{period.payments} payments</p><p className="mt-3 text-[9px] text-[#9b8cff]">ORBIT earned {formatMoney(period.orbitRevenueMinor, portfolio.currency)}</p></div>)}</section>

    <div className="mt-8"><VolumeChart data={portfolio.volume} currency={portfolio.currency} /></div>

    <section className="mt-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[.15em] text-[#8e80ee]">Brand performance</p><h2 className="mt-2 text-[20px] font-semibold tracking-[-.04em] text-white">Your merchant accounts</h2></div><p className="text-[9px] text-[#606571]">Open any brand to inspect its overview, payments, payouts and scans.</p></div><div className="mt-4 grid gap-3 lg:grid-cols-2 2xl:grid-cols-3">{portfolio.brands.map((brand) => <MerchantPortalLink key={brand.id} merchantId={brand.id} href="/dashboard?view=brand" className="group w-full overflow-hidden rounded-[20px] border border-white/[.075] bg-[#0d0f15] p-5 transition hover:border-[#7969ea]/40 hover:bg-[#10121a]" ariaLabel={`Open ${brand.businessName}`}><div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl border border-[#7767e9]/20 bg-[#7564e8]/10 text-[11px] font-semibold text-[#aa9fff]">{brand.businessName.slice(0, 2).toUpperCase()}</span><span className="min-w-0"><span className="block truncate text-[13px] font-medium text-[#e7e8ec]">{brand.businessName}</span><span className={`mt-1 block text-[8px] uppercase tracking-[.12em] ${brand.processorState === "live" ? "text-[#5fc69a]" : "text-[#777c88]"}`}>{brand.processorState === "live" ? "Live financial data" : "Stripe data unavailable"}</span></span></div><ArrowRight className="mt-1 size-4 text-[#575c67] transition group-hover:translate-x-0.5 group-hover:text-[#9b8cff]" /></div><div className="mt-6 grid grid-cols-2 gap-4 border-t border-white/[.06] pt-5"><BrandValue label="Today" value={formatMoney(brand.todayGrossMinor, portfolio.currency)} detail={`${brand.todayPayments} payments`} /><BrandValue label="ORBIT revenue" value={formatMoney(brand.todayOrbitRevenueMinor, portfolio.currency)} detail="Today" /><BrandValue label="30-day volume" value={formatMoney(brand.thirtyDayGrossMinor, portfolio.currency)} /><BrandValue label="Available" value={brand.available.amountMinor === null ? "—" : formatMoney(brand.available.amountMinor, brand.available.currency)} /></div></MerchantPortalLink>)}</div></section>

    <section className="mt-8 overflow-hidden rounded-[20px] border border-white/[.075] bg-[#0c0e14]"><div className="flex items-end justify-between border-b border-white/[.06] px-5 py-5 sm:px-7"><div><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#777c88]">All brands</p><h2 className="mt-2 text-[18px] font-semibold tracking-[-.035em] text-white">Latest successful payments</h2></div><Link href="/dashboard/payments" className="inline-flex items-center gap-1.5 text-[10px] font-semibold text-[#9b8cff]">All payments <ArrowRight className="size-3.5" /></Link></div>{portfolio.recentPayments.length ? portfolio.recentPayments.map((payment) => <MerchantPortalLink key={payment.id} merchantId={payment.merchantId} href={`/dashboard/payments/${encodeURIComponent(payment.publicId)}`} className="grid w-full gap-3 border-b border-white/[.055] px-5 py-4 last:border-0 hover:bg-white/[.02] sm:grid-cols-[140px_1fr_1fr_120px] sm:items-center sm:px-7"><span className="text-[10px] text-[#7d828d]">{formatPortalDateTime(payment.createdAt)}</span><span><span className="block text-[11px] text-[#d0d2d8]">{payment.merchantName}</span><span className="mt-1 block text-[8px] text-[#606571]">Order #{payment.orderId}</span></span><span className="text-[9px] uppercase tracking-[.1em] text-[#686d78]">{payment.source}</span><span className="text-left text-[11px] font-semibold text-white sm:text-right">{formatMoney(payment.amountMinor, payment.currency)}</span></MerchantPortalLink>) : <div className="px-6 py-14 text-center text-[11px] text-[#6c717d]">No successful payments yet.</div>}</section>

    {portfolio.nextPayouts.length > 0 && <section className="mt-8"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#777c88]">Upcoming payouts reported by Stripe</p><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{portfolio.nextPayouts.slice(0, 6).map((payout) => <MerchantPortalLink key={`${payout.merchantId}-${payout.id}`} merchantId={payout.merchantId} href={`/dashboard/payouts/${payout.id}`} className="w-full rounded-[18px] border border-white/[.07] bg-[#0c0e14] p-5"><span className="flex items-center gap-2 text-[10px] text-[#a2a6af]"><Building2 className="size-3.5 text-[#9182f0]" />{payout.merchantName}</span><span className="mt-4 block text-[22px] font-semibold tracking-[-.04em] text-white">{formatMoney(payout.amountMinor, payout.currency)}</span><span className="mt-2 block text-[9px] text-[#6f7480]">Expected {formatPortalDate(payout.arrivalDate)}</span></MerchantPortalLink>)}</div></section>}
  </div>;
}

function AdminMetric({ icon, label, value, detail, featured }: { icon: React.ReactNode; label: string; value: string; detail: string; featured?: boolean }) { return <div className={`relative overflow-hidden rounded-[20px] border p-5 ${featured ? "border-[#7868e8]/30 bg-[linear-gradient(135deg,#171329,#0e1017_68%)]" : "border-white/[.075] bg-[#0d0f15]"}`}><div className="flex items-center gap-2 text-[#9182f0]">{icon}<p className="text-[8px] font-semibold uppercase tracking-[.14em] text-[#777c88]">{label}</p></div><p className="mt-6 text-[27px] font-semibold tracking-[-.05em] text-white">{value}</p><p className="mt-2 text-[9px] text-[#666b77]">{detail}</p></div>; }
function BrandValue({ label, value, detail }: { label: string; value: string; detail?: string }) { return <span><span className="block text-[8px] uppercase tracking-[.12em] text-[#5e636f]">{label}</span><span className="mt-2 block text-[14px] font-semibold text-[#e4e5e9]">{value}</span>{detail && <span className="mt-1 block text-[8px] text-[#5f6470]">{detail}</span>}</span>; }
