import { CalendarDays, CircleDollarSign, ShieldCheck } from "lucide-react";
import type { PortalAvailabilityDay } from "@/merchant-portal/data";
import { formatMoney } from "@/merchant-portal/format";

function calendarDate(timestamp: number) {
  const date = new Date(timestamp * 1000);
  return { month: new Intl.DateTimeFormat("en-US", { month: "short", timeZone: "UTC" }).format(date), day: new Intl.DateTimeFormat("en-US", { day: "2-digit", timeZone: "UTC" }).format(date), long: new Intl.DateTimeFormat("en-US", { month: "long", day: "numeric", year: "numeric", timeZone: "UTC" }).format(date) };
}

export function FundsAvailabilityCalendar({ days, available, pendingMinor }: { days: PortalAvailabilityDay[]; available: boolean; pendingMinor: number | null }) {
  const shown = days.slice(0, 8);
  return <section className="relative mt-4 overflow-hidden rounded-[24px] border border-[#8877ff]/20 bg-[radial-gradient(circle_at_8%_0%,rgba(127,102,242,.18),transparent_30%),#0b0d13] p-6 sm:p-7">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.14em] text-[#9f93f5]"><CalendarDays className="size-3.5" />Processing calendar</p><h2 className="mt-2 text-[20px] font-semibold text-white">When pending funds become available</h2><p className="mt-2 max-w-2xl text-[10px] leading-5 text-[#757b87]">Processor-confirmed balance availability dates. These are not bank transfer dates and ORBIT does not estimate them.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-[#63caa5]/15 bg-[#63caa5]/[.05] px-3 py-2 text-[8px] text-[#82cdb2]"><ShieldCheck className="size-3" />Live availability data</span></div>
    {shown.length ? <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{shown.map((item) => { const date = calendarDate(item.availableOn); return <article key={`${item.availableOn}-${item.currency}`} className="group rounded-[18px] border border-white/[.075] bg-black/25 p-4 transition hover:border-[#8877ff]/30 hover:bg-[#8877ff]/[.045]"><div className="flex items-center gap-3"><span className="grid size-12 shrink-0 place-items-center rounded-xl border border-[#8877ff]/20 bg-[#8877ff]/[.08]"><span className="text-center"><span className="block text-[8px] font-semibold uppercase text-[#a99cff]">{date.month}</span><span className="block text-[17px] font-semibold leading-5 text-white">{date.day}</span></span></span><div><p className="text-[16px] font-semibold text-white">{formatMoney(item.amountMinor, item.currency)}</p><p className="mt-1 text-[8px] text-[#686e79]">{item.transactionCount} processing {item.transactionCount === 1 ? "movement" : "movements"}</p></div></div><p className="mt-4 flex items-center gap-2 border-t border-white/[.06] pt-3 text-[8px] text-[#777d89]"><CircleDollarSign className="size-3 text-[#9182f0]" />Available on {date.long}</p></article>; })}</div> : <div className="mt-6 rounded-[18px] border border-white/[.07] bg-black/20 px-5 py-8 text-center"><p className="text-[12px] font-medium text-[#d7d9df]">{available ? pendingMinor && pendingMinor > 0 ? "Availability date not confirmed yet" : "No funds are currently processing" : "Processing calendar unavailable"}</p><p className="mx-auto mt-2 max-w-lg text-[9px] leading-5 text-[#686e79]">{available ? pendingMinor && pendingMinor > 0 ? "The pending balance is live, but its individual release date has not been returned yet. Refresh later." : "New pending transactions will appear here automatically with their confirmed date." : "ORBIT Payment could not read balance movement dates for this account."}</p></div>}
  </section>;
}
