import { Search } from "lucide-react";
import { PaymentViewTools } from "@/components/merchant-portal/payment-view-tools";

const field = "h-10 w-full rounded-[10px] border border-white/[.08] bg-[#10121a] px-3 text-[10px] text-[#b9bdc6] outline-none focus:border-[#8d80e6]";

export function PaymentFilters({ values }: { values: { query?: string; status?: string; range?: string; from?: string; to?: string } }) {
  return <><form method="get" className="border-b border-white/[.065] px-4 py-4 sm:px-6"><div className="flex flex-col gap-3 xl:flex-row xl:items-center">
    <label className="relative min-w-0 flex-1"><span className="sr-only">Search payments</span><Search className="pointer-events-none absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-[#777d89]" /><input name="query" defaultValue={values.query} placeholder="Search payment, order, email, last 4 or processor reference" className="h-10 w-full rounded-[10px] border border-white/[.08] bg-white/[.025] pl-9 pr-3 text-[11px] text-white outline-none transition placeholder:text-[#626874] focus:border-[#8d80e6] focus:bg-[#10121a] focus:ring-2 focus:ring-[#7969e8]/10" /></label>
    <div className="grid grid-cols-2 gap-2 sm:flex"><label><span className="sr-only">Payment status</span><select name="status" defaultValue={values.status ?? "all"} className={field}><option value="all">All statuses</option><option value="succeeded">Succeeded</option><option value="pending">Pending</option><option value="failed">Failed</option><option value="refunded">Refunded</option><option value="partially_refunded">Partially refunded</option><option value="disputed">Disputed</option></select></label><label><span className="sr-only">Date range</span><select name="range" defaultValue={values.range ?? "30d"} className={field}><option value="all">All time</option><option value="today">Today</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option><option value="custom">Custom range</option></select></label></div>
    <div className="grid grid-cols-2 gap-2"><label className="flex h-10 items-center rounded-[10px] border border-white/[.08] bg-[#10121a] px-3 text-[9px] text-[#777d89]">From<input type="date" name="from" defaultValue={values.from} className="ml-2 min-w-0 bg-transparent text-[10px] text-[#b9bdc6] outline-none [color-scheme:dark]" /></label><label className="flex h-10 items-center rounded-[10px] border border-white/[.08] bg-[#10121a] px-3 text-[9px] text-[#777d89]">To<input type="date" name="to" defaultValue={values.to} className="ml-2 min-w-0 bg-transparent text-[10px] text-[#b9bdc6] outline-none [color-scheme:dark]" /></label></div>
    <button className="h-10 rounded-[10px] bg-gradient-to-r from-[#7158ef] to-[#9277ff] px-5 text-[10px] font-semibold text-white shadow-[0_10px_28px_rgba(124,92,255,.2)] transition hover:brightness-110">Apply filters</button>
  </div></form><PaymentViewTools /></>;
}
