import { BadgeDollarSign, Building2, ReceiptText, RotateCcw, ShieldCheck, Sparkles } from "lucide-react";
import { redirect } from "next/navigation";
import { getPortalContext } from "@/merchant-portal/access";
import { getOrbitEarningsOverview } from "@/merchant-portal/data";
import { formatMoney } from "@/merchant-portal/format";

function feeDate(timestamp: number) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(timestamp * 1000)); }

export default async function OrbitEarningsPage() {
  const { session, merchants } = await getPortalContext();
  if (session.role !== "OWNER") redirect("/dashboard");
  const earnings = await getOrbitEarningsOverview(merchants.map((merchant) => ({ id: merchant.id, businessName: merchant.businessName, portalEnabled: merchant.portalEnabled })));
  const maximum = earnings.available ? Math.max(1, ...earnings.trend.map((point) => point.netMinor)) : 1;

  return <div className="mx-auto w-full max-w-[1480px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.15em] text-[#a99cff]"><Sparkles className="size-3.5" />Private owner view</p><h1 className="mt-3 text-[30px] font-semibold tracking-[-.05em] text-white sm:text-[38px]">ORBIT Earnings</h1><p className="mt-2 text-[11px] text-[#777d89]">Net application fees collected across every ORBIT brand, after fee refunds.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-[#63caa5]/15 bg-[#63caa5]/[.05] px-3 py-2 text-[8px] text-[#82cdb2]"><ShieldCheck className="size-3.5" />Visible only to the workspace owner</span></header>

    {!earnings.available ? <section className="mt-7 rounded-[24px] border border-[#8877ff]/20 bg-[#0b0d13] px-6 py-14 text-center"><BadgeDollarSign className="mx-auto size-7 text-[#9182f0]" /><h2 className="mt-4 text-[17px] font-semibold text-white">Live earnings reconciliation unavailable</h2><p className="mx-auto mt-2 max-w-xl text-[10px] leading-5 text-[#737985]">ORBIT Payment could not read collected application fees. No estimated net earnings are shown. Check the platform credential&apos;s read permission for Application Fees.</p></section> : <>
      <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{earnings.periods.map((period, index) => <article key={period.key} className={`rounded-[22px] border p-5 ${index === 2 ? "border-[#8877ff]/30 bg-[radial-gradient(circle_at_90%_0%,rgba(130,101,255,.2),transparent_38%),#11131b]" : "border-white/[.075] bg-[#0b0d13]"}`}><p className="text-[8px] font-semibold uppercase tracking-[.13em] text-[#717783]">{period.label}</p><p className="mt-4 text-[28px] font-semibold tracking-[-.05em] text-white">{formatMoney(period.netMinor, earnings.currency)}</p><div className="mt-4 flex items-center justify-between border-t border-white/[.06] pt-3 text-[8px] text-[#676d79]"><span>{period.fees} collected fees</span>{period.refundedMinor > 0 && <span className="text-[#d4a06f]">−{formatMoney(period.refundedMinor, earnings.currency)} refunded</span>}</div></article>)}</section>

      <section className="mt-4 grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-[24px] border border-white/[.075] bg-[#0b0d13] p-6"><div className="flex items-center justify-between"><div><p className="text-[8px] font-semibold uppercase tracking-[.13em] text-[#777d89]">Net fee activity</p><h2 className="mt-2 text-[18px] font-semibold text-white">Last 30 days</h2></div><BadgeDollarSign className="size-5 text-[#9182f0]" /></div><div className="mt-7 flex h-44 items-end gap-1.5">{earnings.trend.map((point) => <div key={point.date} className="group relative flex h-full flex-1 items-end"><div className="w-full rounded-t-sm bg-gradient-to-t from-[#6f57e8] to-[#a18cff] opacity-75 transition group-hover:opacity-100" style={{ height: `${Math.max(3, point.netMinor > 0 ? (point.netMinor / maximum) * 100 : 0)}%` }} /><span className="pointer-events-none absolute -top-8 left-1/2 hidden -translate-x-1/2 whitespace-nowrap rounded-md border border-white/[.08] bg-black px-2 py-1 text-[8px] text-white group-hover:block">{formatMoney(point.netMinor, earnings.currency)}</span></div>)}</div></div><div className="rounded-[24px] border border-[#8877ff]/20 bg-[radial-gradient(circle_at_90%_0%,rgba(130,101,255,.18),transparent_42%),#0b0d13] p-6"><p className="flex items-center gap-2 text-[8px] font-semibold uppercase tracking-[.13em] text-[#a99cff]"><ReceiptText className="size-3.5" />Definition</p><h2 className="mt-4 text-[20px] font-semibold text-white">Net means reconciled</h2><p className="mt-3 text-[10px] leading-5 text-[#7b818d]">Gross ORBIT application fees minus any refunded application-fee amount. This view uses the live platform fee ledger and never substitutes merchant sales volume.</p></div></section>

      <section className="mt-4 overflow-hidden rounded-[24px] border border-white/[.075] bg-[#0b0d13]"><div className="border-b border-white/[.07] px-6 py-5"><p className="text-[8px] font-semibold uppercase tracking-[.13em] text-[#777d89]">By brand · last 30 days</p><h2 className="mt-2 text-[18px] font-semibold text-white">Earnings portfolio</h2></div><div className="grid gap-px bg-white/[.055] sm:grid-cols-2 xl:grid-cols-3">{earnings.brands.map((brand) => <article key={brand.merchantId} className="bg-[#0b0d13] p-5"><div className="flex items-center gap-2 text-[10px] text-[#bfc2c9]"><Building2 className="size-3.5 text-[#9182f0]" />{brand.name}</div><p className="mt-4 text-[24px] font-semibold text-white">{formatMoney(brand.netMinor, earnings.currency)}</p><p className="mt-2 text-[8px] text-[#666c78]">{brand.fees} fees · {formatMoney(brand.grossMinor, earnings.currency)} gross{brand.refundedMinor ? ` · ${formatMoney(brand.refundedMinor, earnings.currency)} refunded` : ""}</p></article>)}</div></section>

      <section className="mt-4 overflow-hidden rounded-[24px] border border-white/[.075] bg-[#0b0d13]"><div className="border-b border-white/[.07] px-6 py-5"><p className="text-[8px] font-semibold uppercase tracking-[.13em] text-[#777d89]">Live fee ledger</p><h2 className="mt-2 text-[18px] font-semibold text-white">Recent earnings</h2></div>{earnings.recent.length ? <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-white/[.06] bg-white/[.018]">{["Date", "Brand", "Gross fee", "Refunded", "Net"].map((label) => <th key={label} className="px-6 py-3 text-[8px] font-semibold uppercase text-[#626874]">{label}</th>)}</tr></thead><tbody>{earnings.recent.map((fee) => <tr key={fee.id} className="border-b border-white/[.055] last:border-0 hover:bg-[#8877ff]/[.035]"><td className="px-6 py-4 text-[9px] text-[#747a86]">{feeDate(fee.created)}</td><td className="px-6 py-4 text-[10px] text-[#b9bdc6]">{fee.merchantName}</td><td className="px-6 py-4 text-[10px] text-[#9297a2]">{formatMoney(fee.grossMinor, fee.currency)}</td><td className="px-6 py-4 text-[10px] text-[#c19475]">{fee.refundedMinor ? <span className="inline-flex items-center gap-1"><RotateCcw className="size-3" />{formatMoney(fee.refundedMinor, fee.currency)}</span> : "—"}</td><td className="px-6 py-4 text-[10px] font-semibold text-white">{formatMoney(fee.netMinor, fee.currency)}</td></tr>)}</tbody></table></div> : <div className="px-6 py-16 text-center text-[10px] text-[#707682]">No application fees were collected in the last 12 months.</div>}</section>
    </>}
  </div>;
}
