import { complianceUrlPriority, detectPolicySignals } from "@/sentinel/classification/policy-signals";
import type { CandidateFinding, NormalizedContent, SentinelPageType } from "@/sentinel/types";

interface PageInput { url: string; pageType: SentinelPageType; content: NormalizedContent; httpStatus?: number }

const placeholder = /\b(?:lorem ipsum|your company|example@example\.com|test product|placeholder text|replace this text)\b/i;
const comingSoon = /\b(?:coming soon|under construction|launching soon)\b/i;

function finding(page: PageInput, input: Omit<CandidateFinding, "url" | "pageType">): CandidateFinding { return { ...input, url: page.url, pageType: page.pageType }; }

export function evaluateWebsiteLegitimacy(pages: PageInput[]): CandidateFinding[] {
  if (!pages.length) return [];
  const findings: CandidateFinding[] = [];
  const home = pages.find((page) => page.pageType === "HOME") ?? pages[0];
  if (new URL(home.url).protocol !== "https:") findings.push(finding(home, { ruleKey: "SITE-HTTPS-001", severity: "HIGH", confidence: 1, status: "OPEN", category: "Website legitimacy", title: "Public website is not using HTTPS", description: "The scanned homepage was served over an unencrypted HTTP URL.", reason: "Transport security is directly observable from the requested homepage URL.", recommendedAction: "Serve the complete public website over HTTPS and redirect HTTP requests to the canonical HTTPS origin.", scoreComponent: "POLICY_COVERAGE" }));
  if (home.httpStatus !== undefined && home.httpStatus >= 400) findings.push(finding(home, { ruleKey: "SITE-HOME-001", severity: "HIGH", confidence: 1, status: "OPEN", category: "Website legitimacy", title: "Homepage returned an error response", description: `The homepage returned HTTP ${home.httpStatus}.`, reason: "The root public URL did not return a successful response during the scan.", recommendedAction: "Restore the homepage and verify the production deployment before requesting another scan.", scoreComponent: "POLICY_COVERAGE" }));
  const placeholderPages = pages.filter((page) => (page.httpStatus === undefined || page.httpStatus < 400) && placeholder.test(`${page.content.title} ${page.content.visibleText}`));
  if (placeholderPages.length) findings.push(finding(placeholderPages[0], { ruleKey: "SITE-PLACEHOLDER-001", severity: "MEDIUM", confidence: 0.98, status: "NEEDS_REVIEW", category: "Website legitimacy", title: "Public placeholder content detected", description: `Explicit placeholder text was observed on ${placeholderPages.length} scanned page${placeholderPages.length === 1 ? "" : "s"}.`, detectedText: placeholderPages[0].content.visibleText.match(placeholder)?.[0], affectedUrls: placeholderPages.map((page) => page.url), reason: "The matched wording is a recognized publishing placeholder rather than a judgment about visual design.", recommendedAction: "Replace the placeholder with accurate business information and review all affected URLs.", scoreComponent: "POLICY_COVERAGE" }));
  const products = pages.filter((page) => page.pageType === "PRODUCT" && (page.httpStatus === undefined || page.httpStatus < 400));
  if (comingSoon.test(home.content.visibleText) && products.length === 0) findings.push(finding(home, { ruleKey: "SITE-COMING-SOON-001", severity: "MEDIUM", confidence: 0.94, status: "NEEDS_REVIEW", category: "Website legitimacy", title: "Website appears to be pre-launch", description: "The homepage contains an explicit coming-soon or under-construction message and no accessible product page was classified.", detectedText: home.content.visibleText.match(comingSoon)?.[0], reason: "Both the pre-launch wording and absence of discovered product pages were observed in this scan.", recommendedAction: "Complete the public service description and accessible catalog before relying on the site for business review.", scoreComponent: "POLICY_COVERAGE" }));
  const brokenCriticalPages = pages.filter((page) => (page.httpStatus ?? 0) >= 400 && complianceUrlPriority(page.url) < 20);
  if (brokenCriticalPages.length) findings.push(finding(brokenCriticalPages[0], { ruleKey: "SITE-BROKEN-CRITICAL-001", severity: "MEDIUM", confidence: 1, status: "OPEN", category: "Operational risk", title: "Critical policy or support URL is broken", description: `${brokenCriticalPages.length} policy or support URL${brokenCriticalPages.length === 1 ? "" : "s"} returned an error response.`, affectedUrls: brokenCriticalPages.map((page) => page.url), reason: "Only broken URLs whose slugs identify policy or support functions are included in this finding.", recommendedAction: "Repair or redirect the affected URLs and update persistent navigation links.", scoreComponent: "OPERATIONAL_CONSISTENCY" }));
  const thinPolicies = pages.filter((page) => (page.httpStatus === undefined || page.httpStatus < 400) && detectPolicySignals(page.url, page.content, page.pageType).length > 0 && (page.content.visibleText.length < 120 || placeholder.test(page.content.visibleText)));
  if (thinPolicies.length) findings.push(finding(thinPolicies[0], { ruleKey: "POLICY-QUALITY-001", severity: "LOW", confidence: 0.86, status: "NEEDS_REVIEW", category: "Policy quality", title: "Policy content may be incomplete", description: `${thinPolicies.length} policy page${thinPolicies.length === 1 ? "" : "s"} contained very little primary content or explicit placeholder wording.`, affectedUrls: thinPolicies.map((page) => page.url), reason: "This is a content-completeness signal; ORBIT is not making a legal sufficiency determination.", recommendedAction: "Review the affected policy content for completeness and merchant-specific accuracy.", scoreComponent: "POLICY_COVERAGE" }));
  return findings;
}

