import type { Metadata } from "next";
import { LegalShell } from "@/components/legal/legal-shell";

export const metadata: Metadata = { title: "Terms of Service", description: "Terms governing access to and use of ORBIT B2B software." };

export default function TermsPage() {
  return <LegalShell title="Terms of Service" summary="These terms govern authorized business access to ORBIT's merchant compliance monitoring and risk intelligence software.">
    <h2>1. Agreement and eligibility</h2><p>These Terms of Service form an agreement between the customer accepting an order or using the service and the ORBIT legal entity identified below. You represent that you are authorized to bind the business you act for and that you will use ORBIT only for lawful business purposes.</p>
    <h2>2. The service</h2><p>ORBIT provides B2B software for merchant website monitoring, risk intelligence, policy coverage analysis, change detection, findings management, merchant-health visibility, and audit history. Features may vary by plan, configuration, and technical availability.</p><p>ORBIT is not a bank, acquiring institution, card network, payment processor, legal advisor, or money transmitter. ORBIT does not provide legal determinations and does not guarantee onboarding, underwriting, payment-processing approval, or continued account availability with Stripe or any other provider.</p>
    <h2>3. Accounts and access</h2><p>Customers are responsible for authorized users, access credentials, role assignments, and activity under their workspaces. Credentials must not be shared outside authorized personnel. Customers must promptly notify ORBIT of suspected unauthorized access.</p>
    <h2>4. Customer data and monitored properties</h2><p>Customers retain their rights in information submitted to ORBIT. Customers grant ORBIT the limited rights necessary to host, process, scan, compare, and display that information to provide and secure the service. Customers represent that they have the rights and authority required to configure monitored domains, connect accounts, and provide instructions to ORBIT.</p>
    <h2>5. Acceptable use</h2><p>Customers may not use ORBIT to violate law, infringe rights, access systems without authorization, distribute malicious code, disrupt the service, evade technical limits, reverse engineer protected portions of the service except where law prohibits the restriction, or build a competing product using non-public ORBIT materials.</p>
    <h2>6. Third-party services</h2><p>Optional integrations are governed by the applicable third party&apos;s terms and availability. ORBIT is independent from third-party processors and platforms unless an express written agreement states otherwise. ORBIT is not responsible for third-party approval decisions, service changes, suspensions, or outages.</p>
    <h2>7. Fees, subscription, and taxes</h2><p>Fees, billing cadence, usage limits, and subscription term will be stated in the applicable order form or checkout. Unless stated otherwise, fees exclude taxes and customers are responsible for applicable taxes other than taxes on ORBIT&apos;s income. Failure to pay may result in suspension after applicable notice.</p>
    <h2>8. Confidentiality</h2><p>Each party will protect the other&apos;s non-public business, technical, and commercial information using reasonable care and will use it only to perform under the agreement. Confidentiality obligations do not apply to information that is public without breach, independently developed, lawfully received without restriction, or required to be disclosed by law.</p>
    <h2>9. Intellectual property</h2><p>ORBIT and its licensors retain rights in the service, software, documentation, branding, and related technology. Except for the limited right to use the service during the subscription, no rights are transferred to the customer.</p>
    <h2>10. Service changes and availability</h2><p>ORBIT may improve, modify, or discontinue features. We will seek to avoid materially reducing contracted core functionality during a paid term and will provide notice when commercially reasonable. The service may be unavailable for maintenance, security response, or events beyond reasonable control.</p>
    <h2>11. Disclaimers</h2><p>To the extent permitted by law, the service is provided “as is” and “as available.” Monitoring can reduce blind spots but may not detect every change, issue, claim, or risk. Customers remain responsible for review decisions, legal obligations, merchant management, and use of output.</p>
    <h2>12. Limitation of liability</h2><p>To the extent permitted by law, neither party will be liable for indirect, incidental, special, consequential, or punitive damages, or lost profits, revenue, goodwill, or data. Any aggregate liability cap and exclusions specific to a paid subscription should be set out in the applicable order form or negotiated agreement.</p>
    <h2>13. Termination</h2><p>Either party may terminate for a material breach not cured within a reasonable written cure period. ORBIT may suspend access when necessary to address security risk, unlawful use, or nonpayment. On termination, access ends and data handling follows the agreement and applicable retention obligations.</p>
    <h2>14. Governing terms</h2><p>The governing law, venue, notice process, and any negotiated dispute procedure will be identified in the applicable order form or final production terms once the ORBIT legal entity and business address are configured.</p>
  </LegalShell>;
}
