export const MONTHLY_SERVICE_FEE_USD = 350;
export const PLATFORM_SERVICE_FEE_PERCENT = 3;
export const PLATFORM_SERVICE_FEE_BPS = 300;
export const STANDARD_STRIPE_PROCESSING_FEE_PERCENT = 2.9;
export const TOTAL_TRANSFER_FEE_PERCENT = 5.9;
