import Link from "next/link";
import { ArrowRight, Building2, CalendarClock, WalletCards } from "lucide-react";
import { StatusPill } from "@/components/merchant-portal/status-pill";
import { getPortalContext } from "@/merchant-portal/access";
import { getMerchantPayouts } from "@/merchant-portal/data";
import { formatMoney, formatPortalDate, payoutStatusLabel } from "@/merchant-portal/format";

type Query = { cursor?: string | string[] };

export default async function PayoutsPage({ searchParams }: { searchParams: Promise<Query> }) {
  const [{ merchant }, query] = await Promise.all([getPortalContext(), searchParams]);
  if (!merchant) return null;
  const cursor = typeof query.cursor === "string" ? query.cursor : undefined;
  const result = await getMerchantPayouts(merchant.id, { cursor });
  const nextPayout = result.payouts.filter((payout) => ["pending", "in_transit"].includes(payout.status)).sort((a, b) => a.arrivalDate - b.arrivalDate)[0] ?? null;
  const availableLabel = result.available.amountMinor === null ? "—" : formatMoney(result.available.amountMinor, result.available.currency);
  const pendingLabel = result.pending.amountMinor === null ? "—" : formatMoney(result.pending.amountMinor, result.pending.currency);

  return <div className="mx-auto w-full max-w-[1480px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10">
    <header><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#8e929a]">Money movement</p><h1 className="mt-2 text-[28px] font-semibold tracking-[-.055em] text-[#181a1e] sm:text-[34px]">Payouts</h1><p className="mt-2 text-[12px] text-[#7d8189]">See when your funds are expected and where they are going.</p></header>
    {!result.processorAvailable && <p className="mt-5 rounded-xl border border-[#e6e1c9] bg-[#fbf8e9] px-4 py-3 text-[10px] leading-5 text-[#7b6c3d]">Live payout data is unavailable. ORBIT does not estimate balances, payout amounts or arrival dates.</p>}
    <section className="mt-7 grid gap-4 lg:grid-cols-[.7fr_.7fr_1.35fr]">
      <div className="rounded-[22px] border border-[#dfe1e5] bg-white p-6"><p className="text-[9px] font-semibold uppercase tracking-[.13em] text-[#979ba3]">Available balance</p><p className="mt-6 text-[30px] font-semibold tracking-[-.05em] tabular-nums text-[#22252a]">{availableLabel}</p><p className="mt-2 text-[10px] text-[#8b8f97]">{result.available.amountMinor === null ? "Live balance unavailable" : "Ready for payout"}</p></div>
      <div className="rounded-[22px] border border-[#dfe1e5] bg-[#fbfbfc] p-6"><p className="text-[9px] font-semibold uppercase tracking-[.13em] text-[#979ba3]">Pending balance</p><p className="mt-6 text-[30px] font-semibold tracking-[-.05em] tabular-nums text-[#22252a]">{pendingLabel}</p><p className="mt-2 text-[10px] text-[#8b8f97]">{result.pending.amountMinor === null ? "Live balance unavailable" : "Processing"}</p></div>
      <div className="relative overflow-hidden rounded-[22px] bg-[#1c1e24] p-6 text-white shadow-[0_20px_55px_rgba(24,26,33,.14)] sm:p-7"><div className="absolute -right-12 -top-20 size-56 rounded-full border border-white/[.08]" /><div className="relative"><div className="flex items-center justify-between"><p className="text-[9px] font-semibold uppercase tracking-[.13em] text-[#a1a5ae]">Next payout</p>{nextPayout && <StatusPill status={payoutStatusLabel(nextPayout.status)} />}</div>{nextPayout ? <div className="mt-6 grid gap-5 sm:grid-cols-[1fr_auto]"><div><p className="text-[34px] font-semibold tracking-[-.05em] tabular-nums">{formatMoney(nextPayout.amountMinor, nextPayout.currency)}</p><p className="mt-2 flex items-center gap-2 text-[10px] text-[#a3a7af]"><CalendarClock className="size-3.5 text-[#9487ef]" />Expected {formatPortalDate(nextPayout.arrivalDate)}</p></div><div className="border-t border-white/[.1] pt-4 sm:border-l sm:border-t-0 sm:pl-5 sm:pt-0"><p className="text-[8px] uppercase tracking-[.12em] text-[#81858e]">Destination</p><p className="mt-2 flex items-center gap-2 text-[10px] text-[#c8cad0]"><Building2 className="size-3.5" />{nextPayout.destination}</p></div></div> : <div className="mt-7"><p className="text-[16px] font-semibold">No payout scheduled</p><p className="mt-2 max-w-md text-[10px] leading-5 text-[#969aa3]">Your available funds will be included according to your current payout schedule.</p></div>}</div></div>
    </section>

    <section className="mt-8 overflow-hidden rounded-[20px] border border-[#dfe1e5] bg-white shadow-[0_12px_40px_rgba(29,34,44,.04)]"><div className="border-b border-[#e8e9ec] px-5 py-5 sm:px-7"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#979ba3]">Complete history</p><h2 className="mt-2 text-[18px] font-semibold tracking-[-.035em] text-[#202329]">Payout history</h2></div>{result.payouts.length ? <div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left"><thead><tr className="border-b border-[#e9eaed] bg-[#fafbfc]">{["Date", "Payout ID", "Amount", "Destination", "Arrival", "Status", ""].map((column) => <th key={column} className="px-5 py-3 text-[8px] font-semibold uppercase tracking-[.13em] text-[#999da5] first:pl-7 last:pr-7">{column}</th>)}</tr></thead><tbody>{result.payouts.map((payout) => <tr key={payout.id} className="border-b border-[#eef0f2] last:border-0 hover:bg-[#fafaff]">{[
          formatPortalDate(payout.created), <span key="id" className="font-mono text-[9px] text-[#6254ca]">{payout.id}</span>, <span key="amount" className="font-semibold tabular-nums text-[#34373d]">{formatMoney(payout.amountMinor, payout.currency)}</span>, payout.destination, formatPortalDate(payout.arrivalDate), <StatusPill key="status" status={payoutStatusLabel(payout.status)} />, <ArrowRight key="arrow" className="size-3.5 text-[#b2b5bb]" />,
        ].map((value, index) => <td key={index} className="p-0 text-[10px] text-[#686c74] first:pl-2 last:pr-2"><Link href={`/dashboard/payouts/${payout.id}`} className="block min-h-14 px-3 py-5" aria-label={index === 0 ? `Open payout ${payout.id}` : undefined}>{value}</Link></td>)}</tr>)}</tbody></table></div> : <div className="px-6 py-20 text-center"><span className="mx-auto grid size-11 place-items-center rounded-xl bg-[#f0edff] text-[#7769df]"><WalletCards className="size-4" /></span><h2 className="mt-4 text-[15px] font-semibold text-[#34373d]">No payouts yet</h2><p className="mx-auto mt-2 max-w-sm text-[11px] leading-5 text-[#8b8f97]">Completed and scheduled payouts will appear here as Stripe makes them available.</p></div>}{result.nextCursor && <div className="flex justify-end border-t border-[#e9eaed] px-5 py-4"><Link href={`/dashboard/payouts?cursor=${encodeURIComponent(result.nextCursor)}`} className="inline-flex h-9 items-center gap-2 rounded-[10px] border border-[#dfe1e5] px-3.5 text-[10px] font-medium text-[#5f636b]">Older payouts<ArrowRight className="size-3.5" /></Link></div>}</section>
  </div>;
}
