import { AlertTriangle, CreditCard, Eye, Radar, ShieldAlert, ShieldCheck } from "lucide-react";
import { MerchantPortalLink } from "@/components/merchant-portal/merchant-portal-link";
import { getPortalContext } from "@/merchant-portal/access";
import { formatMoney, formatPortalDateTime } from "@/merchant-portal/format";
import { getPortfolioRisk } from "@/operations/risk";

export default async function RiskPage() {
  const { merchant, merchants, session } = await getPortalContext();
  const portfolio = ["OWNER", "ADMIN"].includes(session.role);
  const scopedMerchants = portfolio ? merchants : merchant ? [merchant] : [];
  const risk = await getPortfolioRisk(scopedMerchants.map((item) => ({ id: item.id, businessName: item.businessName })));
  const cards = [
    { label: "Action required", value: risk.actionable, icon: ShieldAlert, color: "text-[#e8a0a8]" },
    { label: "Disputes · 120 days", value: risk.disputes, icon: AlertTriangle, color: "text-[#d7ad68]" },
    { label: "Open reviews", value: risk.reviews, icon: Eye, color: "text-[#a99cff]" },
    { label: "Early fraud warnings", value: risk.warnings, icon: Radar, color: "text-[#84cfb4]" },
  ];
  return <div className="mx-auto w-full max-w-[1540px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.14em] text-[#a99cff]"><Radar className="size-3.5" />Live processor monitoring</p><h1 className="mt-3 text-[30px] font-semibold tracking-[-.055em] text-white sm:text-[38px]">Risk & disputes</h1><p className="mt-2 text-[11px] text-[#777d89]">A read-only command center for disputes, reviews and early fraud warnings.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-[#63caa5]/15 bg-[#63caa5]/[.05] px-3 py-2 text-[8px] text-[#82cdb2]"><ShieldCheck className="size-3.5" />No payment actions performed</span></header>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card) => { const Icon = card.icon; return <article key={card.label} className="rounded-[20px] border border-white/[.075] bg-[#0b0d13] p-5"><Icon className={`size-4 ${card.color}`} /><p className="mt-6 text-[28px] font-semibold text-white">{card.value}</p><p className="mt-1 text-[9px] uppercase tracking-[.1em] text-[#6b717c]">{card.label}</p></article>; })}</section>
    {risk.atRisk.length > 0 && <div className="mt-4 flex flex-wrap gap-2">{risk.atRisk.map((item) => <span key={item.currency} className="rounded-full border border-[#d7ad68]/15 bg-[#d7ad68]/[.05] px-3 py-2 text-[9px] text-[#c8ac76]">At-risk volume: {formatMoney(item.amountMinor, item.currency)}</span>)}</div>}
    {risk.unavailableMerchants.length > 0 && <div className="mt-5 rounded-2xl border border-[#d7ad68]/15 bg-[#d7ad68]/[.04] px-5 py-4"><p className="text-[10px] font-medium text-[#d0b477]">Some live risk feeds are temporarily unavailable.</p><p className="mt-1 text-[8px] text-[#8c7c5d]">{risk.unavailableMerchants.map((item) => item.merchantName).join(", ")}</p></div>}
    <section className="mt-6 overflow-hidden rounded-[24px] border border-white/[.075] bg-[#0b0d13]"><div className="border-b border-white/[.07] px-5 py-5 sm:px-7"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#777d89]">Risk timeline</p><h2 className="mt-2 text-[18px] font-semibold text-white">Latest signals</h2></div>{risk.items.length ? <div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left"><thead><tr className="border-b border-white/[.06]">{["Type", "Merchant", "Reason", "Status", "Amount", "Created", "Due", "Payment"].map((heading) => <th key={heading} className="px-4 py-3 text-[8px] uppercase tracking-[.08em] text-[#626874] first:pl-7">{heading}</th>)}</tr></thead><tbody>{risk.items.map((item) => <tr key={`${item.kind}:${item.id}`} className="border-b border-white/[.055] last:border-0"><td className="py-4 pl-7 pr-4 text-[9px] capitalize text-[#b4aafa]">{item.kind}</td><td className="px-4 text-[9px] text-[#b7bbc4]">{item.merchantName}</td><td className="px-4 text-[9px] text-[#8a909b]">{item.reason.replaceAll("_", " ")}</td><td className="px-4"><span className="rounded-full border border-white/[.08] px-2 py-1 text-[8px] text-[#d4b578]">{item.status.replaceAll("_", " ")}</span></td><td className="px-4 text-[10px] text-white">{item.amountMinor !== null && item.currency ? formatMoney(item.amountMinor, item.currency) : "—"}</td><td className="px-4 text-[9px] text-[#7c828e]">{formatPortalDateTime(item.createdAt)}</td><td className="px-4 text-[9px] text-[#7c828e]">{item.dueAt ? formatPortalDateTime(item.dueAt) : "—"}</td><td className="px-4">{item.paymentPublicId ? <MerchantPortalLink merchantId={item.merchantId} href={`/dashboard/payments/${encodeURIComponent(item.paymentPublicId)}`} className="inline-flex items-center gap-1.5 text-[9px] font-semibold text-[#9d91f2]"><CreditCard className="size-3" />Open</MerchantPortalLink> : <span className="text-[8px] text-[#565c67]">Not matched</span>}</td></tr>)}</tbody></table></div> : <div className="px-6 py-20 text-center"><ShieldCheck className="mx-auto size-6 text-[#63caa5]" /><h2 className="mt-4 text-[15px] font-semibold text-white">No recent risk signals</h2><p className="mt-2 text-[10px] text-[#6c727e]">No disputes, open reviews or early fraud warnings were returned for the last 120 days.</p></div>}</section>
  </div>;
}
