import type { Metadata } from "next";
import { LegalShell } from "@/components/legal/legal-shell";

export const metadata: Metadata = { title: "Privacy Policy", description: "ORBIT Privacy Policy for its B2B merchant compliance and risk intelligence software." };

export default function PrivacyPage() {
  return <LegalShell title="Privacy Policy" summary="This policy explains how ORBIT handles information in connection with its website, access requests, and B2B software services.">
    <h2>1. Scope</h2><p>This Privacy Policy applies to information processed through the ORBIT marketing website, product access workflows, support channels, and merchant compliance and risk intelligence services. Customer agreements may include additional data-processing terms.</p>
    <h2>2. Information we collect</h2><p>We may collect business contact information such as name, work email, company, role, website, and messages submitted through our forms. In providing the service, ORBIT may process workspace configuration, user access records, merchant website content, scan results, findings, remediation activity, audit events, and operational integration signals selected by a customer.</p><p>ORBIT is designed to minimize collection of sensitive information. Customers should not submit payment-card numbers, government identifiers, health records, or other unnecessary sensitive personal information through general website forms.</p>
    <h2>3. How we use information</h2><ul><li>Provide, secure, maintain, and improve the ORBIT service.</li><li>Respond to access requests, support questions, and product inquiries.</li><li>Monitor system performance, prevent misuse, and verify relevant events.</li><li>Generate website-change intelligence, findings, and audit records as configured by customers.</li><li>Meet contractual, legal, and compliance obligations applicable to ORBIT.</li></ul>
    <h2>4. Legal bases and business use</h2><p>Where applicable law requires a legal basis, ORBIT processes information to perform contracts, pursue legitimate business interests, comply with law, and act on consent when consent is the appropriate basis. ORBIT is intended primarily for business customers and authorized business users.</p>
    <h2>5. Service providers and integrations</h2><p>ORBIT may use infrastructure, security, analytics, communications, and customer-support providers under appropriate contractual restrictions. When a customer enables an integration, information may be exchanged with that provider according to the customer&apos;s configuration and the provider&apos;s terms. Stripe-hosted onboarding may be used when applicable; ORBIT does not need to collect payment credentials handled by Stripe-hosted interfaces.</p>
    <h2>6. Retention</h2><p>We retain information for as long as reasonably necessary to provide the service, preserve customer-configured audit history, resolve disputes, enforce agreements, and meet legal obligations. Retention periods may vary by data type, customer instructions, and contractual terms.</p>
    <h2>7. Security</h2><p>ORBIT is designed to use safeguards such as encryption in transit, role-based access architecture, audit logging, secure webhook verification, and signed API communication where applicable. No method of storage or transmission can be guaranteed completely secure, and this policy does not represent a certification.</p>
    <h2>8. Your choices and rights</h2><p>Depending on location and applicable law, individuals may have rights to request access, correction, deletion, restriction, or portability of personal information, or to object to certain processing. We may need to verify identity and authority before fulfilling a request. Business users may also contact their organization&apos;s workspace administrator.</p>
    <h2>9. International processing</h2><p>Information may be processed in jurisdictions other than the one where it was collected. Where required, ORBIT will use appropriate contractual or legal mechanisms for cross-border transfers.</p>
    <h2>10. Changes to this policy</h2><p>We may update this policy as the service and legal requirements evolve. Material changes will be indicated by an updated effective date and, where appropriate, additional notice.</p>
  </LegalShell>;
}
