import Link from "next/link";
import { ArrowRight, Building2, CalendarClock, ChevronRight, CircleDollarSign, CreditCard, Landmark, ShieldCheck } from "lucide-react";
import { VolumeChart } from "@/components/merchant-portal/volume-chart";
import { getPortalContext } from "@/merchant-portal/access";
import { getMerchantOverview } from "@/merchant-portal/data";
import { formatMoney, formatPortalDate, formatPortalDateTime, paymentStatusLabel, payoutStatusLabel, relativeUpdatedAt } from "@/merchant-portal/format";

export default async function DashboardPage() {
  const { merchant } = await getPortalContext();
  if (!merchant) return <NoMerchant />;
  const overview = await getMerchantOverview(merchant.id);
  const currency = overview.volumeCurrency || overview.statistics.find((item) => item.currency)?.currency || "USD";
  const availableLabel = overview.available.amountMinor === null ? "—" : formatMoney(overview.available.amountMinor, overview.available.currency);
  const pendingLabel = overview.pending.amountMinor === null ? "—" : formatMoney(overview.pending.amountMinor, overview.pending.currency);
  const pendingRatio = overview.pending.amountMinor !== null && overview.available.amountMinor !== null && overview.pending.currency === overview.available.currency && overview.pending.amountMinor + overview.available.amountMinor > 0
    ? Math.round((overview.pending.amountMinor / (overview.pending.amountMinor + overview.available.amountMinor)) * 100)
    : 0;

  return <div className="mx-auto w-full max-w-[1480px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#8e929a]">Financial overview</p><h1 className="mt-2 text-[28px] font-semibold tracking-[-.055em] text-[#181a1e] sm:text-[34px]">Good to see you.</h1><p className="mt-2 text-[12px] text-[#7d8189]">Your balances, sales and upcoming deposits in one place.</p></div><p className="text-[10px] text-[#9a9ea5]">Last updated {relativeUpdatedAt(overview.updatedAt)}</p></header>

    {overview.processorState !== "live" && <div className="mt-6 flex items-start gap-3 rounded-xl border border-[#e2e0f3] bg-[#f4f2ff] px-4 py-3 text-[11px] leading-5 text-[#645d80]"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-[#7567d8]" /><p>{overview.processorState === "not_connected" ? "Connect Stripe to show live balances and payout details. Payment totals below continue to come from verified ORBIT records." : "Live balance and payout details are temporarily unavailable. Verified ORBIT payment totals remain visible."}</p></div>}

    <section className="mt-7 grid gap-4 xl:grid-cols-[1.35fr_.9fr_.72fr]">
      <div className="relative overflow-hidden rounded-[24px] bg-[#191b21] p-6 text-white shadow-[0_20px_50px_rgba(26,28,36,.16)] sm:p-7"><div className="absolute -right-14 -top-20 size-60 rounded-full border border-white/[.08]" /><div className="absolute -right-2 -top-8 size-36 rounded-full border border-[#8574f3]/30" /><div className="relative"><div className="flex items-center gap-2 text-[10px] font-medium uppercase tracking-[.14em] text-[#aeb1ba]"><CircleDollarSign className="size-3.5 text-[#9b8eff]" />Available balance</div><p className="mt-7 text-[40px] font-semibold tracking-[-.055em] tabular-nums sm:text-[48px]">{availableLabel}</p><p className="mt-2 text-[11px] text-[#a6a9b2]">{overview.available.amountMinor === null ? "Live balance unavailable" : "Ready for your next payout"}</p><div className="mt-8 flex items-center gap-2 border-t border-white/[.09] pt-4 text-[10px] text-[#969aa3]"><Landmark className="size-3.5" /><span>{overview.processorState === "live" ? "Funds verified by Stripe" : "Awaiting Stripe balance"}</span></div></div></div>
      <div className="rounded-[24px] border border-[#dedfe4] bg-white p-6 shadow-[0_12px_40px_rgba(29,34,44,.045)] sm:p-7"><div className="flex items-center justify-between"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#92969e]">Next payout</p>{overview.nextPayout && <span className="rounded-full bg-[#f0edff] px-2.5 py-1 text-[9px] font-semibold text-[#6657d3]">{payoutStatusLabel(overview.nextPayout.status)}</span>}</div>{overview.nextPayout ? <><p className="mt-7 text-[30px] font-semibold tracking-[-.05em] tabular-nums">{formatMoney(overview.nextPayout.amountMinor, overview.nextPayout.currency)}</p><div className="mt-6 space-y-3 border-t border-[#eceef0] pt-4"><p className="flex items-center gap-2 text-[11px] text-[#676b73]"><CalendarClock className="size-3.5 text-[#8b7ce8]" />Expected {formatPortalDate(overview.nextPayout.arrivalDate)}</p><p className="flex items-center gap-2 text-[11px] text-[#676b73]"><Building2 className="size-3.5 text-[#8b7ce8]" />{overview.nextPayout.destination}</p></div></> : <div className="mt-9"><p className="text-[17px] font-semibold tracking-[-.03em] text-[#35383e]">No payout scheduled</p><p className="mt-3 max-w-xs text-[11px] leading-5 text-[#858991]">Your available funds will be included according to your current payout schedule.</p></div>}</div>
      <div className="rounded-[24px] border border-[#dedfe4] bg-[#fbfbfc] p-6 shadow-[0_12px_40px_rgba(29,34,44,.035)] sm:p-7"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#92969e]">Pending balance</p><p className="mt-7 text-[30px] font-semibold tracking-[-.05em] tabular-nums text-[#272a30]">{pendingLabel}</p><p className="mt-3 text-[11px] leading-5 text-[#858991]">{overview.pending.amountMinor === null ? "Live balance unavailable." : "Processing before funds become available."}</p><div className="mt-8 h-1.5 overflow-hidden rounded-full bg-[#e8e9ec]"><div className="h-full rounded-full bg-[#9b8def]" style={{ width: `${pendingRatio}%` }} /></div></div>
    </section>

    <section className="mt-8 grid grid-cols-2 border-y border-[#dedfe3] md:grid-cols-4">{overview.statistics.map((stat, index) => <div key={stat.key} className={`py-5 ${index % 2 === 0 ? "pr-4" : "border-l border-[#dedfe3] pl-4"} md:border-l md:px-6 md:first:border-l-0 md:first:pl-0`}><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#989ca4]">{stat.label}</p><p className="mt-3 text-[22px] font-semibold tracking-[-.045em] tabular-nums text-[#25282d]">{stat.currency ? formatMoney(stat.amountMinor, stat.currency) : stat.payments ? "Multiple currencies" : formatMoney(0, currency)}</p><p className="mt-1.5 text-[10px] text-[#8a8e96]">{stat.payments} payment{stat.payments === 1 ? "" : "s"}{stat.averageMinor !== null && stat.currency ? ` · ${formatMoney(stat.averageMinor, stat.currency)} avg` : ""}</p><p className="mt-2 text-[9px] text-[#a2a6ad]">Refunds {stat.refundsMinor === null || !stat.currency ? "—" : formatMoney(stat.refundsMinor, stat.currency)} · Net {stat.netRevenueMinor === null || !stat.currency ? "—" : formatMoney(stat.netRevenueMinor, stat.currency)}</p></div>)}</section>

    <div className="mt-8"><VolumeChart data={overview.volume} currency={currency} /></div>

    <section className="mt-8 rounded-[22px] border border-[#e1e3e7] bg-white shadow-[0_12px_40px_rgba(29,34,44,.04)]"><div className="flex items-end justify-between border-b border-[#eceef0] px-5 py-5 sm:px-7"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#989ca4]">Latest activity</p><h2 className="mt-2 text-[18px] font-semibold tracking-[-.035em] text-[#202329]">Recent payments</h2></div><Link href="/dashboard/payments" className="inline-flex items-center gap-1.5 text-[10px] font-semibold text-[#6556d4]">View all payments <ArrowRight className="size-3.5" /></Link></div>{overview.recentPayments.length ? <div>{overview.recentPayments.map((payment) => <Link key={payment.id} href={`/dashboard/payments/${encodeURIComponent(payment.publicId)}`} className="grid gap-3 border-b border-[#eff0f2] px-5 py-4 transition last:border-0 hover:bg-[#fafaff] sm:grid-cols-[130px_1fr_150px_120px_20px] sm:items-center sm:px-7"><div><p className="text-[11px] font-medium text-[#50545b]">{formatPortalDateTime(payment.createdAt)}</p><p className="mt-1 text-[9px] text-[#a0a4ab]">UTC</p></div><div><p className="text-[12px] font-medium text-[#292c31]">Order #{payment.orderId}</p><p className="mt-1 text-[9px] uppercase tracking-[.08em] text-[#999da5]">{payment.source.toLowerCase()}</p></div><div className="flex items-center gap-2 text-[10px] text-[#6f747c]"><CreditCard className="size-3.5 text-[#9a8fed]" />Payment method</div><div className="sm:text-right"><p className="text-[12px] font-semibold tabular-nums text-[#282b31]">{formatMoney(payment.amountMinor, payment.currency)}</p><p className="mt-1 text-[9px] text-[#4e9b7f]">{paymentStatusLabel(payment.status)}</p></div><ChevronRight className="hidden size-3.5 text-[#b8bbc1] sm:block" /></Link>)}</div> : <div className="px-6 py-14 text-center"><span className="mx-auto grid size-10 place-items-center rounded-xl bg-[#f0edff] text-[#7769df]"><CreditCard className="size-4" /></span><h3 className="mt-4 text-[14px] font-semibold text-[#34373d]">No payments yet</h3><p className="mx-auto mt-2 max-w-sm text-[11px] leading-5 text-[#8b8f97]">Payments will appear here as soon as your first successful transaction is processed through ORBIT.</p></div>}</section>
  </div>;
}

function NoMerchant() {
  return <div className="mx-auto max-w-xl px-6 py-24 text-center"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-[#ece9ff] text-[#6f60dc]"><Building2 className="size-5" /></span><h1 className="mt-5 text-xl font-semibold tracking-[-.04em]">No merchant account assigned</h1><p className="mt-3 text-sm leading-6 text-[#777b84]">Ask your ORBIT workspace administrator to assign your user to a merchant account.</p></div>;
}
