import { Activity, ArrowDownRight, ArrowUpRight, BarChart3, CreditCard, ShieldCheck, UsersRound } from "lucide-react";
import { AnalyticsChart } from "@/components/merchant-portal/analytics-chart";
import { customerMerchantIds } from "@/customers/data";
import { getPortalContext } from "@/merchant-portal/access";
import { formatMoney } from "@/merchant-portal/format";
import { analyticsRange, getPortalAnalytics } from "@/operations/analytics";

const change = (current: number, previous: number) => previous === 0 ? (current ? 100 : 0) : Math.round(((current - previous) / previous) * 100);

export default async function AnalyticsPage({ searchParams }: { searchParams: Promise<{ range?: string | string[] }> }) {
  const [{ merchant, merchants, session }, query] = await Promise.all([getPortalContext(), searchParams]);
  const range = analyticsRange(typeof query.range === "string" ? query.range : undefined);
  const scope = customerMerchantIds(session.role, merchant?.id ?? null, merchants.map((item) => item.id));
  const analytics = await getPortalAnalytics(scope, range);
  const primary = analytics.current[0] ?? { currency: "USD", volumeMinor: 0, successful: 0, failed: 0, total: 0, customers: 0 };
  const previous = analytics.previous.find((item) => item.currency === primary.currency) ?? { volumeMinor: 0, successful: 0, failed: 0, total: 0, customers: 0 };
  const acceptance = primary.total ? Math.round((primary.successful / primary.total) * 1000) / 10 : 0;
  const previousAcceptance = previous.total ? Math.round((previous.successful / previous.total) * 1000) / 10 : 0;
  const cards = [
    { label: "Successful volume", value: formatMoney(primary.volumeMinor, primary.currency), delta: change(primary.volumeMinor, previous.volumeMinor), icon: BarChart3 },
    { label: "Acceptance rate", value: `${acceptance.toFixed(1)}%`, delta: Math.round((acceptance - previousAcceptance) * 10) / 10, icon: ShieldCheck },
    { label: "Successful payments", value: primary.successful.toLocaleString("en-US"), delta: change(primary.successful, previous.successful), icon: CreditCard },
    { label: "Identified customers", value: primary.customers.toLocaleString("en-US"), delta: change(primary.customers, previous.customers), icon: UsersRound },
  ];
  return <div className="mx-auto w-full max-w-[1540px] px-4 py-7 sm:px-7 lg:px-10 lg:py-10"><header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.14em] text-[#a99cff]"><Activity className="size-3.5" />Performance intelligence</p><h1 className="mt-3 text-[30px] font-semibold tracking-[-.055em] text-white sm:text-[38px]">Analytics</h1><p className="mt-2 text-[11px] text-[#777d89]">Payment performance and customer activity compared with the previous period.</p></div><form><select name="range" defaultValue={range} className="h-10 rounded-xl border border-white/[.1] bg-[#101218] px-4 text-[10px] text-[#d8dae0]"><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option></select><button className="ml-2 h-10 rounded-xl bg-[#7868e8]/15 px-4 text-[9px] font-semibold text-[#b8affb]">Apply</button></form></header>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card) => { const Icon = card.icon; const positive = card.delta >= 0; const DeltaIcon = positive ? ArrowUpRight : ArrowDownRight; return <article key={card.label} className="rounded-[20px] border border-white/[.075] bg-[#0b0d13] p-5"><div className="flex items-center justify-between"><Icon className="size-4 text-[#9182f0]" /><span className={`flex items-center gap-1 text-[8px] ${positive ? "text-[#68cba7]" : "text-[#dd8e98]"}`}><DeltaIcon className="size-3" />{Math.abs(card.delta)}%</span></div><p className="mt-6 text-[25px] font-semibold tracking-[-.04em] text-white">{card.value}</p><p className="mt-1 text-[9px] uppercase tracking-[.1em] text-[#6b717c]">{card.label}</p></article>; })}</section>
    <section className="mt-5 rounded-[24px] border border-white/[.075] bg-[#0b0d13] p-5 sm:p-7"><div><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#777d89]">Daily performance</p><h2 className="mt-2 text-[18px] font-semibold text-white">Successful payment volume</h2></div><AnalyticsChart points={analytics.trend} currency={analytics.primaryCurrency} /></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="overflow-hidden rounded-[22px] border border-white/[.075] bg-[#0b0d13]"><div className="border-b border-white/[.06] px-5 py-5"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#777d89]">Currency breakdown</p></div>{analytics.current.length ? analytics.current.map((metric) => <div key={metric.currency} className="grid grid-cols-[1fr_auto] gap-3 border-b border-white/[.055] px-5 py-4 last:border-0"><div><p className="text-[11px] font-medium text-[#dfe1e6]">{metric.currency}</p><p className="mt-1 text-[8px] text-[#676d78]">{metric.successful} successful · {metric.failed} failed</p></div><p className="text-[11px] font-semibold text-white">{formatMoney(metric.volumeMinor, metric.currency)}</p></div>) : <p className="px-5 py-12 text-center text-[10px] text-[#666c78]">No activity for this period.</p>}</div><div className="overflow-hidden rounded-[22px] border border-white/[.075] bg-[#0b0d13]"><div className="border-b border-white/[.06] px-5 py-5"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[#777d89]">Top brands</p></div>{analytics.topMerchants.length ? analytics.topMerchants.map((item) => <div key={`${item.merchantId}:${item.currency}`} className="flex items-center justify-between border-b border-white/[.055] px-5 py-4 last:border-0"><div><p className="text-[10px] text-[#d8dae0]">{item.merchantName}</p><p className="mt-1 text-[8px] text-[#676d78]">{item.payments} payments · {item.currency}</p></div><p className="text-[10px] font-semibold text-white">{formatMoney(item.amountMinor, item.currency)}</p></div>) : <p className="px-5 py-12 text-center text-[10px] text-[#666c78]">No successful brands in this period.</p>}</div></section>
  </div>;
}
